#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice_trm.h"

/* Agnd */
#define Agnd__0__DM__MASK 0x07u
#define Agnd__0__DM__SHIFT 0u
#define Agnd__0__DR CYREG_PRT1_DR
#define Agnd__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Agnd__0__HSIOM_MASK 0x0000000Fu
#define Agnd__0__HSIOM_SHIFT 0u
#define Agnd__0__INTCFG CYREG_PRT1_INTCFG
#define Agnd__0__INTSTAT CYREG_PRT1_INTSTAT
#define Agnd__0__MASK 0x01u
#define Agnd__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Agnd__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Agnd__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Agnd__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Agnd__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Agnd__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Agnd__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Agnd__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Agnd__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Agnd__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Agnd__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Agnd__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Agnd__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Agnd__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Agnd__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Agnd__0__PC CYREG_PRT1_PC
#define Agnd__0__PC2 CYREG_PRT1_PC2
#define Agnd__0__PORT 1u
#define Agnd__0__PS CYREG_PRT1_PS
#define Agnd__0__SHIFT 0u
#define Agnd__DR CYREG_PRT1_DR
#define Agnd__INTCFG CYREG_PRT1_INTCFG
#define Agnd__INTSTAT CYREG_PRT1_INTSTAT
#define Agnd__MASK 0x01u
#define Agnd__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Agnd__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Agnd__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Agnd__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Agnd__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Agnd__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Agnd__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Agnd__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Agnd__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Agnd__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Agnd__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Agnd__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Agnd__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Agnd__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Agnd__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Agnd__PC CYREG_PRT1_PC
#define Agnd__PC2 CYREG_PRT1_PC2
#define Agnd__PORT 1u
#define Agnd__PS CYREG_PRT1_PS
#define Agnd__SHIFT 0u

/* P1_6 */
#define P1_6__0__DM__MASK 0x1C0000u
#define P1_6__0__DM__SHIFT 18u
#define P1_6__0__DR CYREG_PRT1_DR
#define P1_6__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define P1_6__0__HSIOM_MASK 0x0F000000u
#define P1_6__0__HSIOM_SHIFT 24u
#define P1_6__0__INTCFG CYREG_PRT1_INTCFG
#define P1_6__0__INTSTAT CYREG_PRT1_INTSTAT
#define P1_6__0__MASK 0x40u
#define P1_6__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define P1_6__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define P1_6__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define P1_6__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define P1_6__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define P1_6__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define P1_6__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define P1_6__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define P1_6__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define P1_6__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define P1_6__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define P1_6__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define P1_6__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define P1_6__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define P1_6__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define P1_6__0__PC CYREG_PRT1_PC
#define P1_6__0__PC2 CYREG_PRT1_PC2
#define P1_6__0__PORT 1u
#define P1_6__0__PS CYREG_PRT1_PS
#define P1_6__0__SHIFT 6u
#define P1_6__DR CYREG_PRT1_DR
#define P1_6__INTCFG CYREG_PRT1_INTCFG
#define P1_6__INTSTAT CYREG_PRT1_INTSTAT
#define P1_6__MASK 0x40u
#define P1_6__PA__CFG0 CYREG_UDB_PA1_CFG0
#define P1_6__PA__CFG1 CYREG_UDB_PA1_CFG1
#define P1_6__PA__CFG10 CYREG_UDB_PA1_CFG10
#define P1_6__PA__CFG11 CYREG_UDB_PA1_CFG11
#define P1_6__PA__CFG12 CYREG_UDB_PA1_CFG12
#define P1_6__PA__CFG13 CYREG_UDB_PA1_CFG13
#define P1_6__PA__CFG14 CYREG_UDB_PA1_CFG14
#define P1_6__PA__CFG2 CYREG_UDB_PA1_CFG2
#define P1_6__PA__CFG3 CYREG_UDB_PA1_CFG3
#define P1_6__PA__CFG4 CYREG_UDB_PA1_CFG4
#define P1_6__PA__CFG5 CYREG_UDB_PA1_CFG5
#define P1_6__PA__CFG6 CYREG_UDB_PA1_CFG6
#define P1_6__PA__CFG7 CYREG_UDB_PA1_CFG7
#define P1_6__PA__CFG8 CYREG_UDB_PA1_CFG8
#define P1_6__PA__CFG9 CYREG_UDB_PA1_CFG9
#define P1_6__PC CYREG_PRT1_PC
#define P1_6__PC2 CYREG_PRT1_PC2
#define P1_6__PORT 1u
#define P1_6__PS CYREG_PRT1_PS
#define P1_6__SHIFT 6u

/* PWM_1_cy_m0s8_tcpwm_1 */
#define PWM_1_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT1_CC
#define PWM_1_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT1_CC_BUFF
#define PWM_1_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT1_COUNTER
#define PWM_1_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT1_CTRL
#define PWM_1_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT1_INTR
#define PWM_1_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT1_INTR_MASK
#define PWM_1_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT1_INTR_MASKED
#define PWM_1_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT1_INTR_SET
#define PWM_1_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT1_PERIOD
#define PWM_1_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT1_PERIOD_BUFF
#define PWM_1_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT1_STATUS
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x02u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 1u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x200u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 9u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x2000000u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 25u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x20000u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 17u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x02u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 1u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x02u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 1u
#define PWM_1_cy_m0s8_tcpwm_1__TCPWM_NUMBER 1u
#define PWM_1_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT1_TR_CTRL0
#define PWM_1_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT1_TR_CTRL1
#define PWM_1_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT1_TR_CTRL2

/* UD_Ref */
#define UD_Ref__0__DM__MASK 0x38000u
#define UD_Ref__0__DM__SHIFT 15u
#define UD_Ref__0__DR CYREG_PRT2_DR
#define UD_Ref__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define UD_Ref__0__HSIOM_MASK 0x00F00000u
#define UD_Ref__0__HSIOM_SHIFT 20u
#define UD_Ref__0__INTCFG CYREG_PRT2_INTCFG
#define UD_Ref__0__INTSTAT CYREG_PRT2_INTSTAT
#define UD_Ref__0__MASK 0x20u
#define UD_Ref__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define UD_Ref__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define UD_Ref__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define UD_Ref__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define UD_Ref__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define UD_Ref__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define UD_Ref__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define UD_Ref__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define UD_Ref__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define UD_Ref__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define UD_Ref__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define UD_Ref__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define UD_Ref__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define UD_Ref__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define UD_Ref__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define UD_Ref__0__PC CYREG_PRT2_PC
#define UD_Ref__0__PC2 CYREG_PRT2_PC2
#define UD_Ref__0__PORT 2u
#define UD_Ref__0__PS CYREG_PRT2_PS
#define UD_Ref__0__SHIFT 5u
#define UD_Ref__DR CYREG_PRT2_DR
#define UD_Ref__INTCFG CYREG_PRT2_INTCFG
#define UD_Ref__INTSTAT CYREG_PRT2_INTSTAT
#define UD_Ref__MASK 0x20u
#define UD_Ref__PA__CFG0 CYREG_UDB_PA2_CFG0
#define UD_Ref__PA__CFG1 CYREG_UDB_PA2_CFG1
#define UD_Ref__PA__CFG10 CYREG_UDB_PA2_CFG10
#define UD_Ref__PA__CFG11 CYREG_UDB_PA2_CFG11
#define UD_Ref__PA__CFG12 CYREG_UDB_PA2_CFG12
#define UD_Ref__PA__CFG13 CYREG_UDB_PA2_CFG13
#define UD_Ref__PA__CFG14 CYREG_UDB_PA2_CFG14
#define UD_Ref__PA__CFG2 CYREG_UDB_PA2_CFG2
#define UD_Ref__PA__CFG3 CYREG_UDB_PA2_CFG3
#define UD_Ref__PA__CFG4 CYREG_UDB_PA2_CFG4
#define UD_Ref__PA__CFG5 CYREG_UDB_PA2_CFG5
#define UD_Ref__PA__CFG6 CYREG_UDB_PA2_CFG6
#define UD_Ref__PA__CFG7 CYREG_UDB_PA2_CFG7
#define UD_Ref__PA__CFG8 CYREG_UDB_PA2_CFG8
#define UD_Ref__PA__CFG9 CYREG_UDB_PA2_CFG9
#define UD_Ref__PC CYREG_PRT2_PC
#define UD_Ref__PC2 CYREG_PRT2_PC2
#define UD_Ref__PORT 2u
#define UD_Ref__PS CYREG_PRT2_PS
#define UD_Ref__SHIFT 5u

/* UpDown_CounterUDB */
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_A0_REG CYREG_UDB_W16_A0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_A1_REG CYREG_UDB_W16_A1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_D0_REG CYREG_UDB_W16_D0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_D1_REG CYREG_UDB_W16_D1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_00
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_F0_REG CYREG_UDB_W16_F0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__16BIT_F1_REG CYREG_UDB_W16_F1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_A0_REG CYREG_UDB_W32_A0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_A1_REG CYREG_UDB_W32_A1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_D0_REG CYREG_UDB_W32_D0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_D1_REG CYREG_UDB_W32_D1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_DP_AUX_CTL_REG CYREG_UDB_W32_ACTL_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_F0_REG CYREG_UDB_W32_F0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__32BIT_F1_REG CYREG_UDB_W32_F1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__A0_A1_REG CYREG_UDB_CAT16_A_00
#define UpDown_CounterUDB_sC32_counterdp_u0__A0_REG CYREG_UDB_W8_A0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__A1_REG CYREG_UDB_W8_A1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__D0_D1_REG CYREG_UDB_CAT16_D_00
#define UpDown_CounterUDB_sC32_counterdp_u0__D0_REG CYREG_UDB_W8_D0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__D1_REG CYREG_UDB_W8_D1_00
#define UpDown_CounterUDB_sC32_counterdp_u0__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_00
#define UpDown_CounterUDB_sC32_counterdp_u0__F0_F1_REG CYREG_UDB_CAT16_F_00
#define UpDown_CounterUDB_sC32_counterdp_u0__F0_REG CYREG_UDB_W8_F0_00
#define UpDown_CounterUDB_sC32_counterdp_u0__F1_REG CYREG_UDB_W8_F1_00
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_A0_REG CYREG_UDB_W16_A0_01
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_A1_REG CYREG_UDB_W16_A1_01
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_D0_REG CYREG_UDB_W16_D0_01
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_D1_REG CYREG_UDB_W16_D1_01
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_F0_REG CYREG_UDB_W16_F0_01
#define UpDown_CounterUDB_sC32_counterdp_u1__16BIT_F1_REG CYREG_UDB_W16_F1_01
#define UpDown_CounterUDB_sC32_counterdp_u1__A0_A1_REG CYREG_UDB_CAT16_A_01
#define UpDown_CounterUDB_sC32_counterdp_u1__A0_REG CYREG_UDB_W8_A0_01
#define UpDown_CounterUDB_sC32_counterdp_u1__A1_REG CYREG_UDB_W8_A1_01
#define UpDown_CounterUDB_sC32_counterdp_u1__D0_D1_REG CYREG_UDB_CAT16_D_01
#define UpDown_CounterUDB_sC32_counterdp_u1__D0_REG CYREG_UDB_W8_D0_01
#define UpDown_CounterUDB_sC32_counterdp_u1__D1_REG CYREG_UDB_W8_D1_01
#define UpDown_CounterUDB_sC32_counterdp_u1__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define UpDown_CounterUDB_sC32_counterdp_u1__F0_F1_REG CYREG_UDB_CAT16_F_01
#define UpDown_CounterUDB_sC32_counterdp_u1__F0_REG CYREG_UDB_W8_F0_01
#define UpDown_CounterUDB_sC32_counterdp_u1__F1_REG CYREG_UDB_W8_F1_01
#define UpDown_CounterUDB_sC32_counterdp_u1__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define UpDown_CounterUDB_sC32_counterdp_u1__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_A0_REG CYREG_UDB_W16_A0_02
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_A1_REG CYREG_UDB_W16_A1_02
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_D0_REG CYREG_UDB_W16_D0_02
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_D1_REG CYREG_UDB_W16_D1_02
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_F0_REG CYREG_UDB_W16_F0_02
#define UpDown_CounterUDB_sC32_counterdp_u2__16BIT_F1_REG CYREG_UDB_W16_F1_02
#define UpDown_CounterUDB_sC32_counterdp_u2__A0_A1_REG CYREG_UDB_CAT16_A_02
#define UpDown_CounterUDB_sC32_counterdp_u2__A0_REG CYREG_UDB_W8_A0_02
#define UpDown_CounterUDB_sC32_counterdp_u2__A1_REG CYREG_UDB_W8_A1_02
#define UpDown_CounterUDB_sC32_counterdp_u2__D0_D1_REG CYREG_UDB_CAT16_D_02
#define UpDown_CounterUDB_sC32_counterdp_u2__D0_REG CYREG_UDB_W8_D0_02
#define UpDown_CounterUDB_sC32_counterdp_u2__D1_REG CYREG_UDB_W8_D1_02
#define UpDown_CounterUDB_sC32_counterdp_u2__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define UpDown_CounterUDB_sC32_counterdp_u2__F0_F1_REG CYREG_UDB_CAT16_F_02
#define UpDown_CounterUDB_sC32_counterdp_u2__F0_REG CYREG_UDB_W8_F0_02
#define UpDown_CounterUDB_sC32_counterdp_u2__F1_REG CYREG_UDB_W8_F1_02
#define UpDown_CounterUDB_sC32_counterdp_u2__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define UpDown_CounterUDB_sC32_counterdp_u2__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define UpDown_CounterUDB_sC32_counterdp_u3__A0_A1_REG CYREG_UDB_CAT16_A_03
#define UpDown_CounterUDB_sC32_counterdp_u3__A0_REG CYREG_UDB_W8_A0_03
#define UpDown_CounterUDB_sC32_counterdp_u3__A1_REG CYREG_UDB_W8_A1_03
#define UpDown_CounterUDB_sC32_counterdp_u3__D0_D1_REG CYREG_UDB_CAT16_D_03
#define UpDown_CounterUDB_sC32_counterdp_u3__D0_REG CYREG_UDB_W8_D0_03
#define UpDown_CounterUDB_sC32_counterdp_u3__D1_REG CYREG_UDB_W8_D1_03
#define UpDown_CounterUDB_sC32_counterdp_u3__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_03
#define UpDown_CounterUDB_sC32_counterdp_u3__F0_F1_REG CYREG_UDB_CAT16_F_03
#define UpDown_CounterUDB_sC32_counterdp_u3__F0_REG CYREG_UDB_W8_F0_03
#define UpDown_CounterUDB_sC32_counterdp_u3__F1_REG CYREG_UDB_W8_F1_03
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__7__MASK 0x80u
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__7__POS 7
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG CYREG_UDB_W8_CTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_REG CYREG_UDB_W8_CTL_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__MASK 0x80u
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define UpDown_CounterUDB_sCTRLReg_SyncCtl_ctrlreg__PERIOD_REG CYREG_UDB_W8_MSK_01
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__0__MASK 0x01u
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__0__POS 0
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__1__MASK 0x02u
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__1__POS 1
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__2__MASK 0x04u
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__2__POS 2
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__3__MASK 0x08u
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__3__POS 3
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__5__MASK 0x20u
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__5__POS 5
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__6__MASK 0x40u
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__6__POS 6
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__MASK 0x6Fu
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__MASK_REG CYREG_UDB_W8_MSK_03
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_03
#define UpDown_CounterUDB_sSTSReg_rstSts_stsreg__STATUS_REG CYREG_UDB_W8_ST_03

/* PWM_Pin */
#define PWM_Pin__0__DM__MASK 0x07u
#define PWM_Pin__0__DM__SHIFT 0u
#define PWM_Pin__0__DR CYREG_PRT3_DR
#define PWM_Pin__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define PWM_Pin__0__HSIOM_MASK 0x0000000Fu
#define PWM_Pin__0__HSIOM_SHIFT 0u
#define PWM_Pin__0__INTCFG CYREG_PRT3_INTCFG
#define PWM_Pin__0__INTSTAT CYREG_PRT3_INTSTAT
#define PWM_Pin__0__MASK 0x01u
#define PWM_Pin__0__OUT_SEL CYREG_UDB_PA3_CFG10
#define PWM_Pin__0__OUT_SEL_SHIFT 0u
#define PWM_Pin__0__OUT_SEL_VAL 1u
#define PWM_Pin__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define PWM_Pin__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define PWM_Pin__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define PWM_Pin__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define PWM_Pin__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define PWM_Pin__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define PWM_Pin__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define PWM_Pin__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define PWM_Pin__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define PWM_Pin__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define PWM_Pin__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define PWM_Pin__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define PWM_Pin__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define PWM_Pin__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define PWM_Pin__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define PWM_Pin__0__PC CYREG_PRT3_PC
#define PWM_Pin__0__PC2 CYREG_PRT3_PC2
#define PWM_Pin__0__PORT 3u
#define PWM_Pin__0__PS CYREG_PRT3_PS
#define PWM_Pin__0__SHIFT 0u
#define PWM_Pin__DR CYREG_PRT3_DR
#define PWM_Pin__INTCFG CYREG_PRT3_INTCFG
#define PWM_Pin__INTSTAT CYREG_PRT3_INTSTAT
#define PWM_Pin__MASK 0x01u
#define PWM_Pin__PA__CFG0 CYREG_UDB_PA3_CFG0
#define PWM_Pin__PA__CFG1 CYREG_UDB_PA3_CFG1
#define PWM_Pin__PA__CFG10 CYREG_UDB_PA3_CFG10
#define PWM_Pin__PA__CFG11 CYREG_UDB_PA3_CFG11
#define PWM_Pin__PA__CFG12 CYREG_UDB_PA3_CFG12
#define PWM_Pin__PA__CFG13 CYREG_UDB_PA3_CFG13
#define PWM_Pin__PA__CFG14 CYREG_UDB_PA3_CFG14
#define PWM_Pin__PA__CFG2 CYREG_UDB_PA3_CFG2
#define PWM_Pin__PA__CFG3 CYREG_UDB_PA3_CFG3
#define PWM_Pin__PA__CFG4 CYREG_UDB_PA3_CFG4
#define PWM_Pin__PA__CFG5 CYREG_UDB_PA3_CFG5
#define PWM_Pin__PA__CFG6 CYREG_UDB_PA3_CFG6
#define PWM_Pin__PA__CFG7 CYREG_UDB_PA3_CFG7
#define PWM_Pin__PA__CFG8 CYREG_UDB_PA3_CFG8
#define PWM_Pin__PA__CFG9 CYREG_UDB_PA3_CFG9
#define PWM_Pin__PC CYREG_PRT3_PC
#define PWM_Pin__PC2 CYREG_PRT3_PC2
#define PWM_Pin__PORT 3u
#define PWM_Pin__PS CYREG_PRT3_PS
#define PWM_Pin__SHIFT 0u

/* CapSense_Cmod */
#define CapSense_Cmod__0__DM__MASK 0x1C0u
#define CapSense_Cmod__0__DM__SHIFT 6u
#define CapSense_Cmod__0__DR CYREG_PRT4_DR
#define CapSense_Cmod__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define CapSense_Cmod__0__HSIOM_MASK 0x00000F00u
#define CapSense_Cmod__0__HSIOM_SHIFT 8u
#define CapSense_Cmod__0__INTCFG CYREG_PRT4_INTCFG
#define CapSense_Cmod__0__INTSTAT CYREG_PRT4_INTSTAT
#define CapSense_Cmod__0__MASK 0x04u
#define CapSense_Cmod__0__PC CYREG_PRT4_PC
#define CapSense_Cmod__0__PC2 CYREG_PRT4_PC2
#define CapSense_Cmod__0__PORT 4u
#define CapSense_Cmod__0__PS CYREG_PRT4_PS
#define CapSense_Cmod__0__SHIFT 2u
#define CapSense_Cmod__Cmod__DM__MASK 0x1C0u
#define CapSense_Cmod__Cmod__DM__SHIFT 6u
#define CapSense_Cmod__Cmod__DR CYREG_PRT4_DR
#define CapSense_Cmod__Cmod__INTCFG CYREG_PRT4_INTCFG
#define CapSense_Cmod__Cmod__INTSTAT CYREG_PRT4_INTSTAT
#define CapSense_Cmod__Cmod__MASK 0x04u
#define CapSense_Cmod__Cmod__PC CYREG_PRT4_PC
#define CapSense_Cmod__Cmod__PC2 CYREG_PRT4_PC2
#define CapSense_Cmod__Cmod__PORT 4u
#define CapSense_Cmod__Cmod__PS CYREG_PRT4_PS
#define CapSense_Cmod__Cmod__SHIFT 2u
#define CapSense_Cmod__DR CYREG_PRT4_DR
#define CapSense_Cmod__INTCFG CYREG_PRT4_INTCFG
#define CapSense_Cmod__INTSTAT CYREG_PRT4_INTSTAT
#define CapSense_Cmod__MASK 0x04u
#define CapSense_Cmod__PC CYREG_PRT4_PC
#define CapSense_Cmod__PC2 CYREG_PRT4_PC2
#define CapSense_Cmod__PORT 4u
#define CapSense_Cmod__PS CYREG_PRT4_PS
#define CapSense_Cmod__SHIFT 2u

/* CapSense_CSD_FFB */
#define CapSense_CSD_FFB__CSD_CONFIG CYREG_CSD_CONFIG
#define CapSense_CSD_FFB__CSD_COUNTER CYREG_CSD_COUNTER
#define CapSense_CSD_FFB__CSD_ID CYREG_CSD_ID
#define CapSense_CSD_FFB__CSD_INTR CYREG_CSD_INTR
#define CapSense_CSD_FFB__CSD_INTR_SET CYREG_CSD_INTR_SET
#define CapSense_CSD_FFB__CSD_NUMBER 0u
#define CapSense_CSD_FFB__CSD_STATUS CYREG_CSD_STATUS

/* CapSense_IDAC1_cy_psoc4_idac */
#define CapSense_IDAC1_cy_psoc4_idac__CONTROL CYREG_CSD_CONFIG
#define CapSense_IDAC1_cy_psoc4_idac__CSD_IDAC CYREG_CSD_IDAC
#define CapSense_IDAC1_cy_psoc4_idac__CSD_IDAC_SHIFT 0u
#define CapSense_IDAC1_cy_psoc4_idac__CSD_TRIM1 CYREG_CSD_TRIM1
#define CapSense_IDAC1_cy_psoc4_idac__CSD_TRIM1_SHIFT 0u
#define CapSense_IDAC1_cy_psoc4_idac__CSD_TRIM2 CYREG_CSD_TRIM2
#define CapSense_IDAC1_cy_psoc4_idac__CSD_TRIM2_SHIFT 0u
#define CapSense_IDAC1_cy_psoc4_idac__IDAC_NUMBER 1u
#define CapSense_IDAC1_cy_psoc4_idac__POLARITY CYREG_CSD_CONFIG
#define CapSense_IDAC1_cy_psoc4_idac__POLARITY_SHIFT 16u

/* CapSense_IDAC2_cy_psoc4_idac */
#define CapSense_IDAC2_cy_psoc4_idac__CONTROL CYREG_CSD_CONFIG
#define CapSense_IDAC2_cy_psoc4_idac__CSD_IDAC CYREG_CSD_IDAC
#define CapSense_IDAC2_cy_psoc4_idac__CSD_IDAC_SHIFT 16u
#define CapSense_IDAC2_cy_psoc4_idac__CSD_TRIM1 CYREG_CSD_TRIM1
#define CapSense_IDAC2_cy_psoc4_idac__CSD_TRIM1_SHIFT 4u
#define CapSense_IDAC2_cy_psoc4_idac__CSD_TRIM2 CYREG_CSD_TRIM2
#define CapSense_IDAC2_cy_psoc4_idac__CSD_TRIM2_SHIFT 4u
#define CapSense_IDAC2_cy_psoc4_idac__IDAC_NUMBER 2u
#define CapSense_IDAC2_cy_psoc4_idac__POLARITY CYREG_CSD_CONFIG
#define CapSense_IDAC2_cy_psoc4_idac__POLARITY_SHIFT 17u

/* CapSense_ISR */
#define CapSense_ISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define CapSense_ISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define CapSense_ISR__INTC_MASK 0x8000u
#define CapSense_ISR__INTC_NUMBER 15u
#define CapSense_ISR__INTC_PRIOR_MASK 0xC0000000u
#define CapSense_ISR__INTC_PRIOR_NUM 3u
#define CapSense_ISR__INTC_PRIOR_REG CYREG_CM0_IPR3
#define CapSense_ISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define CapSense_ISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* CapSense_SampleClk */
#define CapSense_SampleClk__DIVIDER_MASK 0x0000FFFFu
#define CapSense_SampleClk__ENABLE CYREG_CLK_DIVIDER_A00
#define CapSense_SampleClk__ENABLE_MASK 0x80000000u
#define CapSense_SampleClk__MASK 0x80000000u
#define CapSense_SampleClk__REGISTER CYREG_CLK_DIVIDER_A00

/* CapSense_SenseClk */
#define CapSense_SenseClk__DIVIDER_MASK 0x0000FFFFu
#define CapSense_SenseClk__ENABLE CYREG_CLK_DIVIDER_B00
#define CapSense_SenseClk__ENABLE_MASK 0x80000000u
#define CapSense_SenseClk__MASK 0x80000000u
#define CapSense_SenseClk__REGISTER CYREG_CLK_DIVIDER_B00

/* CapSense_Sns */
#define CapSense_Sns__0__DM__MASK 0x38u
#define CapSense_Sns__0__DM__SHIFT 3u
#define CapSense_Sns__0__DR CYREG_PRT3_DR
#define CapSense_Sns__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define CapSense_Sns__0__HSIOM_MASK 0x000000F0u
#define CapSense_Sns__0__HSIOM_SHIFT 4u
#define CapSense_Sns__0__INTCFG CYREG_PRT3_INTCFG
#define CapSense_Sns__0__INTSTAT CYREG_PRT3_INTSTAT
#define CapSense_Sns__0__MASK 0x02u
#define CapSense_Sns__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define CapSense_Sns__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define CapSense_Sns__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define CapSense_Sns__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define CapSense_Sns__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define CapSense_Sns__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define CapSense_Sns__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define CapSense_Sns__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define CapSense_Sns__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define CapSense_Sns__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define CapSense_Sns__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define CapSense_Sns__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define CapSense_Sns__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define CapSense_Sns__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define CapSense_Sns__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define CapSense_Sns__0__PC CYREG_PRT3_PC
#define CapSense_Sns__0__PC2 CYREG_PRT3_PC2
#define CapSense_Sns__0__PORT 3u
#define CapSense_Sns__0__PS CYREG_PRT3_PS
#define CapSense_Sns__0__SHIFT 1u
#define CapSense_Sns__Button0__BTN__DM__MASK 0x38u
#define CapSense_Sns__Button0__BTN__DM__SHIFT 3u
#define CapSense_Sns__Button0__BTN__DR CYREG_PRT3_DR
#define CapSense_Sns__Button0__BTN__INTCFG CYREG_PRT3_INTCFG
#define CapSense_Sns__Button0__BTN__INTSTAT CYREG_PRT3_INTSTAT
#define CapSense_Sns__Button0__BTN__MASK 0x02u
#define CapSense_Sns__Button0__BTN__PA__CFG0 CYREG_UDB_PA3_CFG0
#define CapSense_Sns__Button0__BTN__PA__CFG1 CYREG_UDB_PA3_CFG1
#define CapSense_Sns__Button0__BTN__PA__CFG10 CYREG_UDB_PA3_CFG10
#define CapSense_Sns__Button0__BTN__PA__CFG11 CYREG_UDB_PA3_CFG11
#define CapSense_Sns__Button0__BTN__PA__CFG12 CYREG_UDB_PA3_CFG12
#define CapSense_Sns__Button0__BTN__PA__CFG13 CYREG_UDB_PA3_CFG13
#define CapSense_Sns__Button0__BTN__PA__CFG14 CYREG_UDB_PA3_CFG14
#define CapSense_Sns__Button0__BTN__PA__CFG2 CYREG_UDB_PA3_CFG2
#define CapSense_Sns__Button0__BTN__PA__CFG3 CYREG_UDB_PA3_CFG3
#define CapSense_Sns__Button0__BTN__PA__CFG4 CYREG_UDB_PA3_CFG4
#define CapSense_Sns__Button0__BTN__PA__CFG5 CYREG_UDB_PA3_CFG5
#define CapSense_Sns__Button0__BTN__PA__CFG6 CYREG_UDB_PA3_CFG6
#define CapSense_Sns__Button0__BTN__PA__CFG7 CYREG_UDB_PA3_CFG7
#define CapSense_Sns__Button0__BTN__PA__CFG8 CYREG_UDB_PA3_CFG8
#define CapSense_Sns__Button0__BTN__PA__CFG9 CYREG_UDB_PA3_CFG9
#define CapSense_Sns__Button0__BTN__PC CYREG_PRT3_PC
#define CapSense_Sns__Button0__BTN__PC2 CYREG_PRT3_PC2
#define CapSense_Sns__Button0__BTN__PORT 3u
#define CapSense_Sns__Button0__BTN__PS CYREG_PRT3_PS
#define CapSense_Sns__Button0__BTN__SHIFT 1u
#define CapSense_Sns__DR CYREG_PRT3_DR
#define CapSense_Sns__INTCFG CYREG_PRT3_INTCFG
#define CapSense_Sns__INTSTAT CYREG_PRT3_INTSTAT
#define CapSense_Sns__MASK 0x02u
#define CapSense_Sns__PA__CFG0 CYREG_UDB_PA3_CFG0
#define CapSense_Sns__PA__CFG1 CYREG_UDB_PA3_CFG1
#define CapSense_Sns__PA__CFG10 CYREG_UDB_PA3_CFG10
#define CapSense_Sns__PA__CFG11 CYREG_UDB_PA3_CFG11
#define CapSense_Sns__PA__CFG12 CYREG_UDB_PA3_CFG12
#define CapSense_Sns__PA__CFG13 CYREG_UDB_PA3_CFG13
#define CapSense_Sns__PA__CFG14 CYREG_UDB_PA3_CFG14
#define CapSense_Sns__PA__CFG2 CYREG_UDB_PA3_CFG2
#define CapSense_Sns__PA__CFG3 CYREG_UDB_PA3_CFG3
#define CapSense_Sns__PA__CFG4 CYREG_UDB_PA3_CFG4
#define CapSense_Sns__PA__CFG5 CYREG_UDB_PA3_CFG5
#define CapSense_Sns__PA__CFG6 CYREG_UDB_PA3_CFG6
#define CapSense_Sns__PA__CFG7 CYREG_UDB_PA3_CFG7
#define CapSense_Sns__PA__CFG8 CYREG_UDB_PA3_CFG8
#define CapSense_Sns__PA__CFG9 CYREG_UDB_PA3_CFG9
#define CapSense_Sns__PC CYREG_PRT3_PC
#define CapSense_Sns__PC2 CYREG_PRT3_PC2
#define CapSense_Sns__PORT 3u
#define CapSense_Sns__PS CYREG_PRT3_PS
#define CapSense_Sns__SHIFT 1u

/* Feedback */
#define Feedback__0__DM__MASK 0x1C0u
#define Feedback__0__DM__SHIFT 6u
#define Feedback__0__DR CYREG_PRT1_DR
#define Feedback__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Feedback__0__HSIOM_MASK 0x00000F00u
#define Feedback__0__HSIOM_SHIFT 8u
#define Feedback__0__INTCFG CYREG_PRT1_INTCFG
#define Feedback__0__INTSTAT CYREG_PRT1_INTSTAT
#define Feedback__0__MASK 0x04u
#define Feedback__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Feedback__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Feedback__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Feedback__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Feedback__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Feedback__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Feedback__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Feedback__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Feedback__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Feedback__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Feedback__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Feedback__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Feedback__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Feedback__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Feedback__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Feedback__0__PC CYREG_PRT1_PC
#define Feedback__0__PC2 CYREG_PRT1_PC2
#define Feedback__0__PORT 1u
#define Feedback__0__PS CYREG_PRT1_PS
#define Feedback__0__SHIFT 2u
#define Feedback__DR CYREG_PRT1_DR
#define Feedback__INTCFG CYREG_PRT1_INTCFG
#define Feedback__INTSTAT CYREG_PRT1_INTSTAT
#define Feedback__MASK 0x04u
#define Feedback__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Feedback__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Feedback__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Feedback__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Feedback__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Feedback__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Feedback__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Feedback__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Feedback__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Feedback__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Feedback__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Feedback__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Feedback__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Feedback__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Feedback__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Feedback__PC CYREG_PRT1_PC
#define Feedback__PC2 CYREG_PRT1_PC2
#define Feedback__PORT 1u
#define Feedback__PS CYREG_PRT1_PS
#define Feedback__SHIFT 2u

/* Step_A_N */
#define Step_A_N__0__DM__MASK 0x38u
#define Step_A_N__0__DM__SHIFT 3u
#define Step_A_N__0__DR CYREG_PRT2_DR
#define Step_A_N__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Step_A_N__0__HSIOM_MASK 0x000000F0u
#define Step_A_N__0__HSIOM_SHIFT 4u
#define Step_A_N__0__INTCFG CYREG_PRT2_INTCFG
#define Step_A_N__0__INTSTAT CYREG_PRT2_INTSTAT
#define Step_A_N__0__MASK 0x02u
#define Step_A_N__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Step_A_N__0__OUT_SEL_SHIFT 2u
#define Step_A_N__0__OUT_SEL_VAL 0u
#define Step_A_N__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_A_N__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_A_N__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_A_N__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_A_N__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_A_N__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_A_N__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_A_N__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_A_N__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_A_N__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_A_N__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_A_N__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_A_N__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_A_N__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_A_N__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_A_N__0__PC CYREG_PRT2_PC
#define Step_A_N__0__PC2 CYREG_PRT2_PC2
#define Step_A_N__0__PORT 2u
#define Step_A_N__0__PS CYREG_PRT2_PS
#define Step_A_N__0__SHIFT 1u
#define Step_A_N__DR CYREG_PRT2_DR
#define Step_A_N__INTCFG CYREG_PRT2_INTCFG
#define Step_A_N__INTSTAT CYREG_PRT2_INTSTAT
#define Step_A_N__MASK 0x02u
#define Step_A_N__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_A_N__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_A_N__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_A_N__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_A_N__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_A_N__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_A_N__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_A_N__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_A_N__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_A_N__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_A_N__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_A_N__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_A_N__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_A_N__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_A_N__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_A_N__PC CYREG_PRT2_PC
#define Step_A_N__PC2 CYREG_PRT2_PC2
#define Step_A_N__PORT 2u
#define Step_A_N__PS CYREG_PRT2_PS
#define Step_A_N__SHIFT 1u

/* Step_A_P */
#define Step_A_P__0__DM__MASK 0x07u
#define Step_A_P__0__DM__SHIFT 0u
#define Step_A_P__0__DR CYREG_PRT2_DR
#define Step_A_P__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Step_A_P__0__HSIOM_MASK 0x0000000Fu
#define Step_A_P__0__HSIOM_SHIFT 0u
#define Step_A_P__0__INTCFG CYREG_PRT2_INTCFG
#define Step_A_P__0__INTSTAT CYREG_PRT2_INTSTAT
#define Step_A_P__0__MASK 0x01u
#define Step_A_P__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Step_A_P__0__OUT_SEL_SHIFT 0u
#define Step_A_P__0__OUT_SEL_VAL 1u
#define Step_A_P__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_A_P__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_A_P__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_A_P__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_A_P__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_A_P__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_A_P__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_A_P__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_A_P__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_A_P__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_A_P__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_A_P__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_A_P__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_A_P__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_A_P__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_A_P__0__PC CYREG_PRT2_PC
#define Step_A_P__0__PC2 CYREG_PRT2_PC2
#define Step_A_P__0__PORT 2u
#define Step_A_P__0__PS CYREG_PRT2_PS
#define Step_A_P__0__SHIFT 0u
#define Step_A_P__DR CYREG_PRT2_DR
#define Step_A_P__INTCFG CYREG_PRT2_INTCFG
#define Step_A_P__INTSTAT CYREG_PRT2_INTSTAT
#define Step_A_P__MASK 0x01u
#define Step_A_P__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_A_P__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_A_P__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_A_P__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_A_P__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_A_P__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_A_P__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_A_P__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_A_P__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_A_P__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_A_P__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_A_P__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_A_P__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_A_P__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_A_P__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_A_P__PC CYREG_PRT2_PC
#define Step_A_P__PC2 CYREG_PRT2_PC2
#define Step_A_P__PORT 2u
#define Step_A_P__PS CYREG_PRT2_PS
#define Step_A_P__SHIFT 0u

/* Step_B_N */
#define Step_B_N__0__DM__MASK 0xE00u
#define Step_B_N__0__DM__SHIFT 9u
#define Step_B_N__0__DR CYREG_PRT2_DR
#define Step_B_N__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Step_B_N__0__HSIOM_MASK 0x0000F000u
#define Step_B_N__0__HSIOM_SHIFT 12u
#define Step_B_N__0__INTCFG CYREG_PRT2_INTCFG
#define Step_B_N__0__INTSTAT CYREG_PRT2_INTSTAT
#define Step_B_N__0__MASK 0x08u
#define Step_B_N__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Step_B_N__0__OUT_SEL_SHIFT 6u
#define Step_B_N__0__OUT_SEL_VAL 2u
#define Step_B_N__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_B_N__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_B_N__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_B_N__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_B_N__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_B_N__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_B_N__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_B_N__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_B_N__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_B_N__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_B_N__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_B_N__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_B_N__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_B_N__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_B_N__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_B_N__0__PC CYREG_PRT2_PC
#define Step_B_N__0__PC2 CYREG_PRT2_PC2
#define Step_B_N__0__PORT 2u
#define Step_B_N__0__PS CYREG_PRT2_PS
#define Step_B_N__0__SHIFT 3u
#define Step_B_N__DR CYREG_PRT2_DR
#define Step_B_N__INTCFG CYREG_PRT2_INTCFG
#define Step_B_N__INTSTAT CYREG_PRT2_INTSTAT
#define Step_B_N__MASK 0x08u
#define Step_B_N__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_B_N__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_B_N__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_B_N__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_B_N__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_B_N__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_B_N__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_B_N__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_B_N__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_B_N__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_B_N__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_B_N__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_B_N__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_B_N__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_B_N__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_B_N__PC CYREG_PRT2_PC
#define Step_B_N__PC2 CYREG_PRT2_PC2
#define Step_B_N__PORT 2u
#define Step_B_N__PS CYREG_PRT2_PS
#define Step_B_N__SHIFT 3u

/* Step_B_P */
#define Step_B_P__0__DM__MASK 0x1C0u
#define Step_B_P__0__DM__SHIFT 6u
#define Step_B_P__0__DR CYREG_PRT2_DR
#define Step_B_P__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Step_B_P__0__HSIOM_MASK 0x00000F00u
#define Step_B_P__0__HSIOM_SHIFT 8u
#define Step_B_P__0__INTCFG CYREG_PRT2_INTCFG
#define Step_B_P__0__INTSTAT CYREG_PRT2_INTSTAT
#define Step_B_P__0__MASK 0x04u
#define Step_B_P__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Step_B_P__0__OUT_SEL_SHIFT 4u
#define Step_B_P__0__OUT_SEL_VAL 3u
#define Step_B_P__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_B_P__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_B_P__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_B_P__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_B_P__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_B_P__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_B_P__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_B_P__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_B_P__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_B_P__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_B_P__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_B_P__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_B_P__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_B_P__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_B_P__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_B_P__0__PC CYREG_PRT2_PC
#define Step_B_P__0__PC2 CYREG_PRT2_PC2
#define Step_B_P__0__PORT 2u
#define Step_B_P__0__PS CYREG_PRT2_PS
#define Step_B_P__0__SHIFT 2u
#define Step_B_P__DR CYREG_PRT2_DR
#define Step_B_P__INTCFG CYREG_PRT2_INTCFG
#define Step_B_P__INTSTAT CYREG_PRT2_INTSTAT
#define Step_B_P__MASK 0x04u
#define Step_B_P__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Step_B_P__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Step_B_P__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Step_B_P__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Step_B_P__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Step_B_P__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Step_B_P__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Step_B_P__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Step_B_P__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Step_B_P__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Step_B_P__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Step_B_P__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Step_B_P__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Step_B_P__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Step_B_P__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Step_B_P__PC CYREG_PRT2_PC
#define Step_B_P__PC2 CYREG_PRT2_PC2
#define Step_B_P__PORT 2u
#define Step_B_P__PS CYREG_PRT2_PS
#define Step_B_P__SHIFT 2u

/* Sum_node */
#define Sum_node__0__DM__MASK 0x38u
#define Sum_node__0__DM__SHIFT 3u
#define Sum_node__0__DR CYREG_PRT1_DR
#define Sum_node__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Sum_node__0__HSIOM_MASK 0x000000F0u
#define Sum_node__0__HSIOM_SHIFT 4u
#define Sum_node__0__INTCFG CYREG_PRT1_INTCFG
#define Sum_node__0__INTSTAT CYREG_PRT1_INTSTAT
#define Sum_node__0__MASK 0x02u
#define Sum_node__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Sum_node__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Sum_node__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Sum_node__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Sum_node__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Sum_node__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Sum_node__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Sum_node__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Sum_node__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Sum_node__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Sum_node__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Sum_node__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Sum_node__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Sum_node__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Sum_node__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Sum_node__0__PC CYREG_PRT1_PC
#define Sum_node__0__PC2 CYREG_PRT1_PC2
#define Sum_node__0__PORT 1u
#define Sum_node__0__PS CYREG_PRT1_PS
#define Sum_node__0__SHIFT 1u
#define Sum_node__DR CYREG_PRT1_DR
#define Sum_node__INTCFG CYREG_PRT1_INTCFG
#define Sum_node__INTSTAT CYREG_PRT1_INTSTAT
#define Sum_node__MASK 0x02u
#define Sum_node__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Sum_node__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Sum_node__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Sum_node__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Sum_node__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Sum_node__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Sum_node__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Sum_node__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Sum_node__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Sum_node__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Sum_node__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Sum_node__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Sum_node__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Sum_node__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Sum_node__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Sum_node__PC CYREG_PRT1_PC
#define Sum_node__PC2 CYREG_PRT1_PC2
#define Sum_node__PORT 1u
#define Sum_node__PS CYREG_PRT1_PS
#define Sum_node__SHIFT 1u

/* Analog_In */
#define Analog_In__0__DM__MASK 0xE00000u
#define Analog_In__0__DM__SHIFT 21u
#define Analog_In__0__DR CYREG_PRT2_DR
#define Analog_In__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Analog_In__0__HSIOM_MASK 0xF0000000u
#define Analog_In__0__HSIOM_SHIFT 28u
#define Analog_In__0__INTCFG CYREG_PRT2_INTCFG
#define Analog_In__0__INTSTAT CYREG_PRT2_INTSTAT
#define Analog_In__0__MASK 0x80u
#define Analog_In__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Analog_In__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Analog_In__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Analog_In__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Analog_In__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Analog_In__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Analog_In__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Analog_In__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Analog_In__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Analog_In__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Analog_In__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Analog_In__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Analog_In__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Analog_In__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Analog_In__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Analog_In__0__PC CYREG_PRT2_PC
#define Analog_In__0__PC2 CYREG_PRT2_PC2
#define Analog_In__0__PORT 2u
#define Analog_In__0__PS CYREG_PRT2_PS
#define Analog_In__0__SHIFT 7u
#define Analog_In__1__DM__MASK 0x1C0000u
#define Analog_In__1__DM__SHIFT 18u
#define Analog_In__1__DR CYREG_PRT2_DR
#define Analog_In__1__HSIOM CYREG_HSIOM_PORT_SEL2
#define Analog_In__1__HSIOM_MASK 0x0F000000u
#define Analog_In__1__HSIOM_SHIFT 24u
#define Analog_In__1__INTCFG CYREG_PRT2_INTCFG
#define Analog_In__1__INTSTAT CYREG_PRT2_INTSTAT
#define Analog_In__1__MASK 0x40u
#define Analog_In__1__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Analog_In__1__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Analog_In__1__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Analog_In__1__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Analog_In__1__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Analog_In__1__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Analog_In__1__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Analog_In__1__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Analog_In__1__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Analog_In__1__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Analog_In__1__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Analog_In__1__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Analog_In__1__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Analog_In__1__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Analog_In__1__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Analog_In__1__PC CYREG_PRT2_PC
#define Analog_In__1__PC2 CYREG_PRT2_PC2
#define Analog_In__1__PORT 2u
#define Analog_In__1__PS CYREG_PRT2_PS
#define Analog_In__1__SHIFT 6u
#define Analog_In__DR CYREG_PRT2_DR
#define Analog_In__INTCFG CYREG_PRT2_INTCFG
#define Analog_In__INTSTAT CYREG_PRT2_INTSTAT
#define Analog_In__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Analog_In__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Analog_In__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Analog_In__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Analog_In__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Analog_In__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Analog_In__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Analog_In__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Analog_In__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Analog_In__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Analog_In__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Analog_In__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Analog_In__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Analog_In__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Analog_In__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Analog_In__PC CYREG_PRT2_PC
#define Analog_In__PC2 CYREG_PRT2_PC2
#define Analog_In__PORT 2u
#define Analog_In__PS CYREG_PRT2_PS

/* Button_in */
#define Button_in__0__DM__MASK 0xE00000u
#define Button_in__0__DM__SHIFT 21u
#define Button_in__0__DR CYREG_PRT0_DR
#define Button_in__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Button_in__0__HSIOM_MASK 0xF0000000u
#define Button_in__0__HSIOM_SHIFT 28u
#define Button_in__0__INTCFG CYREG_PRT0_INTCFG
#define Button_in__0__INTSTAT CYREG_PRT0_INTSTAT
#define Button_in__0__MASK 0x80u
#define Button_in__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Button_in__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Button_in__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Button_in__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Button_in__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Button_in__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Button_in__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Button_in__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Button_in__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Button_in__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Button_in__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Button_in__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Button_in__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Button_in__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Button_in__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Button_in__0__PC CYREG_PRT0_PC
#define Button_in__0__PC2 CYREG_PRT0_PC2
#define Button_in__0__PORT 0u
#define Button_in__0__PS CYREG_PRT0_PS
#define Button_in__0__SHIFT 7u
#define Button_in__DR CYREG_PRT0_DR
#define Button_in__INTCFG CYREG_PRT0_INTCFG
#define Button_in__INTSTAT CYREG_PRT0_INTSTAT
#define Button_in__MASK 0x80u
#define Button_in__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Button_in__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Button_in__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Button_in__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Button_in__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Button_in__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Button_in__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Button_in__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Button_in__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Button_in__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Button_in__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Button_in__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Button_in__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Button_in__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Button_in__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Button_in__PC CYREG_PRT0_PC
#define Button_in__PC2 CYREG_PRT0_PC2
#define Button_in__PORT 0u
#define Button_in__PS CYREG_PRT0_PS
#define Button_in__SHIFT 7u

/* I2CMaster_SCB */
#define I2CMaster_SCB__BIST_CONTROL CYREG_SCB1_BIST_CONTROL
#define I2CMaster_SCB__BIST_DATA CYREG_SCB1_BIST_DATA
#define I2CMaster_SCB__CTRL CYREG_SCB1_CTRL
#define I2CMaster_SCB__EZ_DATA00 CYREG_SCB1_EZ_DATA00
#define I2CMaster_SCB__EZ_DATA01 CYREG_SCB1_EZ_DATA01
#define I2CMaster_SCB__EZ_DATA02 CYREG_SCB1_EZ_DATA02
#define I2CMaster_SCB__EZ_DATA03 CYREG_SCB1_EZ_DATA03
#define I2CMaster_SCB__EZ_DATA04 CYREG_SCB1_EZ_DATA04
#define I2CMaster_SCB__EZ_DATA05 CYREG_SCB1_EZ_DATA05
#define I2CMaster_SCB__EZ_DATA06 CYREG_SCB1_EZ_DATA06
#define I2CMaster_SCB__EZ_DATA07 CYREG_SCB1_EZ_DATA07
#define I2CMaster_SCB__EZ_DATA08 CYREG_SCB1_EZ_DATA08
#define I2CMaster_SCB__EZ_DATA09 CYREG_SCB1_EZ_DATA09
#define I2CMaster_SCB__EZ_DATA10 CYREG_SCB1_EZ_DATA10
#define I2CMaster_SCB__EZ_DATA11 CYREG_SCB1_EZ_DATA11
#define I2CMaster_SCB__EZ_DATA12 CYREG_SCB1_EZ_DATA12
#define I2CMaster_SCB__EZ_DATA13 CYREG_SCB1_EZ_DATA13
#define I2CMaster_SCB__EZ_DATA14 CYREG_SCB1_EZ_DATA14
#define I2CMaster_SCB__EZ_DATA15 CYREG_SCB1_EZ_DATA15
#define I2CMaster_SCB__EZ_DATA16 CYREG_SCB1_EZ_DATA16
#define I2CMaster_SCB__EZ_DATA17 CYREG_SCB1_EZ_DATA17
#define I2CMaster_SCB__EZ_DATA18 CYREG_SCB1_EZ_DATA18
#define I2CMaster_SCB__EZ_DATA19 CYREG_SCB1_EZ_DATA19
#define I2CMaster_SCB__EZ_DATA20 CYREG_SCB1_EZ_DATA20
#define I2CMaster_SCB__EZ_DATA21 CYREG_SCB1_EZ_DATA21
#define I2CMaster_SCB__EZ_DATA22 CYREG_SCB1_EZ_DATA22
#define I2CMaster_SCB__EZ_DATA23 CYREG_SCB1_EZ_DATA23
#define I2CMaster_SCB__EZ_DATA24 CYREG_SCB1_EZ_DATA24
#define I2CMaster_SCB__EZ_DATA25 CYREG_SCB1_EZ_DATA25
#define I2CMaster_SCB__EZ_DATA26 CYREG_SCB1_EZ_DATA26
#define I2CMaster_SCB__EZ_DATA27 CYREG_SCB1_EZ_DATA27
#define I2CMaster_SCB__EZ_DATA28 CYREG_SCB1_EZ_DATA28
#define I2CMaster_SCB__EZ_DATA29 CYREG_SCB1_EZ_DATA29
#define I2CMaster_SCB__EZ_DATA30 CYREG_SCB1_EZ_DATA30
#define I2CMaster_SCB__EZ_DATA31 CYREG_SCB1_EZ_DATA31
#define I2CMaster_SCB__I2C_CFG CYREG_SCB1_I2C_CFG
#define I2CMaster_SCB__I2C_CTRL CYREG_SCB1_I2C_CTRL
#define I2CMaster_SCB__I2C_M_CMD CYREG_SCB1_I2C_M_CMD
#define I2CMaster_SCB__I2C_S_CMD CYREG_SCB1_I2C_S_CMD
#define I2CMaster_SCB__I2C_STATUS CYREG_SCB1_I2C_STATUS
#define I2CMaster_SCB__INTR_CAUSE CYREG_SCB1_INTR_CAUSE
#define I2CMaster_SCB__INTR_I2C_EC CYREG_SCB1_INTR_I2C_EC
#define I2CMaster_SCB__INTR_I2C_EC_MASK CYREG_SCB1_INTR_I2C_EC_MASK
#define I2CMaster_SCB__INTR_I2C_EC_MASKED CYREG_SCB1_INTR_I2C_EC_MASKED
#define I2CMaster_SCB__INTR_M CYREG_SCB1_INTR_M
#define I2CMaster_SCB__INTR_M_MASK CYREG_SCB1_INTR_M_MASK
#define I2CMaster_SCB__INTR_M_MASKED CYREG_SCB1_INTR_M_MASKED
#define I2CMaster_SCB__INTR_M_SET CYREG_SCB1_INTR_M_SET
#define I2CMaster_SCB__INTR_RX CYREG_SCB1_INTR_RX
#define I2CMaster_SCB__INTR_RX_MASK CYREG_SCB1_INTR_RX_MASK
#define I2CMaster_SCB__INTR_RX_MASKED CYREG_SCB1_INTR_RX_MASKED
#define I2CMaster_SCB__INTR_RX_SET CYREG_SCB1_INTR_RX_SET
#define I2CMaster_SCB__INTR_S CYREG_SCB1_INTR_S
#define I2CMaster_SCB__INTR_S_MASK CYREG_SCB1_INTR_S_MASK
#define I2CMaster_SCB__INTR_S_MASKED CYREG_SCB1_INTR_S_MASKED
#define I2CMaster_SCB__INTR_S_SET CYREG_SCB1_INTR_S_SET
#define I2CMaster_SCB__INTR_SPI_EC CYREG_SCB1_INTR_SPI_EC
#define I2CMaster_SCB__INTR_SPI_EC_MASK CYREG_SCB1_INTR_SPI_EC_MASK
#define I2CMaster_SCB__INTR_SPI_EC_MASKED CYREG_SCB1_INTR_SPI_EC_MASKED
#define I2CMaster_SCB__INTR_TX CYREG_SCB1_INTR_TX
#define I2CMaster_SCB__INTR_TX_MASK CYREG_SCB1_INTR_TX_MASK
#define I2CMaster_SCB__INTR_TX_MASKED CYREG_SCB1_INTR_TX_MASKED
#define I2CMaster_SCB__INTR_TX_SET CYREG_SCB1_INTR_TX_SET
#define I2CMaster_SCB__RX_CTRL CYREG_SCB1_RX_CTRL
#define I2CMaster_SCB__RX_FIFO_CTRL CYREG_SCB1_RX_FIFO_CTRL
#define I2CMaster_SCB__RX_FIFO_RD CYREG_SCB1_RX_FIFO_RD
#define I2CMaster_SCB__RX_FIFO_RD_SILENT CYREG_SCB1_RX_FIFO_RD_SILENT
#define I2CMaster_SCB__RX_FIFO_STATUS CYREG_SCB1_RX_FIFO_STATUS
#define I2CMaster_SCB__RX_MATCH CYREG_SCB1_RX_MATCH
#define I2CMaster_SCB__SPI_CTRL CYREG_SCB1_SPI_CTRL
#define I2CMaster_SCB__SPI_STATUS CYREG_SCB1_SPI_STATUS
#define I2CMaster_SCB__SS0_POSISTION 0u
#define I2CMaster_SCB__SS1_POSISTION 1u
#define I2CMaster_SCB__SS2_POSISTION 2u
#define I2CMaster_SCB__SS3_POSISTION 3u
#define I2CMaster_SCB__STATUS CYREG_SCB1_STATUS
#define I2CMaster_SCB__TX_CTRL CYREG_SCB1_TX_CTRL
#define I2CMaster_SCB__TX_FIFO_CTRL CYREG_SCB1_TX_FIFO_CTRL
#define I2CMaster_SCB__TX_FIFO_STATUS CYREG_SCB1_TX_FIFO_STATUS
#define I2CMaster_SCB__TX_FIFO_WR CYREG_SCB1_TX_FIFO_WR
#define I2CMaster_SCB__UART_CTRL CYREG_SCB1_UART_CTRL
#define I2CMaster_SCB__UART_RX_CTRL CYREG_SCB1_UART_RX_CTRL
#define I2CMaster_SCB__UART_RX_STATUS CYREG_SCB1_UART_RX_STATUS
#define I2CMaster_SCB__UART_TX_CTRL CYREG_SCB1_UART_TX_CTRL

/* I2CMaster_SCB_IRQ */
#define I2CMaster_SCB_IRQ__INTC_CLR_EN_REG CYREG_CM0_ICER
#define I2CMaster_SCB_IRQ__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define I2CMaster_SCB_IRQ__INTC_MASK 0x800u
#define I2CMaster_SCB_IRQ__INTC_NUMBER 11u
#define I2CMaster_SCB_IRQ__INTC_PRIOR_MASK 0xC0000000u
#define I2CMaster_SCB_IRQ__INTC_PRIOR_NUM 3u
#define I2CMaster_SCB_IRQ__INTC_PRIOR_REG CYREG_CM0_IPR2
#define I2CMaster_SCB_IRQ__INTC_SET_EN_REG CYREG_CM0_ISER
#define I2CMaster_SCB_IRQ__INTC_SET_PD_REG CYREG_CM0_ISPR

/* I2CMaster_SCBCLK */
#define I2CMaster_SCBCLK__DIVIDER_MASK 0x0000FFFFu
#define I2CMaster_SCBCLK__ENABLE CYREG_CLK_DIVIDER_C01
#define I2CMaster_SCBCLK__ENABLE_MASK 0x80000000u
#define I2CMaster_SCBCLK__MASK 0x80000000u
#define I2CMaster_SCBCLK__REGISTER CYREG_CLK_DIVIDER_C01

/* I2CMaster_scl */
#define I2CMaster_scl__0__DM__MASK 0x7000u
#define I2CMaster_scl__0__DM__SHIFT 12u
#define I2CMaster_scl__0__DR CYREG_PRT0_DR
#define I2CMaster_scl__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define I2CMaster_scl__0__HSIOM_GPIO 0u
#define I2CMaster_scl__0__HSIOM_I2C 14u
#define I2CMaster_scl__0__HSIOM_I2C_SCL 14u
#define I2CMaster_scl__0__HSIOM_MASK 0x000F0000u
#define I2CMaster_scl__0__HSIOM_SHIFT 16u
#define I2CMaster_scl__0__HSIOM_SPI 15u
#define I2CMaster_scl__0__HSIOM_SPI_MOSI 15u
#define I2CMaster_scl__0__HSIOM_UART 9u
#define I2CMaster_scl__0__HSIOM_UART_RX 9u
#define I2CMaster_scl__0__INTCFG CYREG_PRT0_INTCFG
#define I2CMaster_scl__0__INTSTAT CYREG_PRT0_INTSTAT
#define I2CMaster_scl__0__MASK 0x10u
#define I2CMaster_scl__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define I2CMaster_scl__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define I2CMaster_scl__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define I2CMaster_scl__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define I2CMaster_scl__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define I2CMaster_scl__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define I2CMaster_scl__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define I2CMaster_scl__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define I2CMaster_scl__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define I2CMaster_scl__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define I2CMaster_scl__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define I2CMaster_scl__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define I2CMaster_scl__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define I2CMaster_scl__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define I2CMaster_scl__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define I2CMaster_scl__0__PC CYREG_PRT0_PC
#define I2CMaster_scl__0__PC2 CYREG_PRT0_PC2
#define I2CMaster_scl__0__PORT 0u
#define I2CMaster_scl__0__PS CYREG_PRT0_PS
#define I2CMaster_scl__0__SHIFT 4u
#define I2CMaster_scl__DR CYREG_PRT0_DR
#define I2CMaster_scl__INTCFG CYREG_PRT0_INTCFG
#define I2CMaster_scl__INTSTAT CYREG_PRT0_INTSTAT
#define I2CMaster_scl__MASK 0x10u
#define I2CMaster_scl__PA__CFG0 CYREG_UDB_PA0_CFG0
#define I2CMaster_scl__PA__CFG1 CYREG_UDB_PA0_CFG1
#define I2CMaster_scl__PA__CFG10 CYREG_UDB_PA0_CFG10
#define I2CMaster_scl__PA__CFG11 CYREG_UDB_PA0_CFG11
#define I2CMaster_scl__PA__CFG12 CYREG_UDB_PA0_CFG12
#define I2CMaster_scl__PA__CFG13 CYREG_UDB_PA0_CFG13
#define I2CMaster_scl__PA__CFG14 CYREG_UDB_PA0_CFG14
#define I2CMaster_scl__PA__CFG2 CYREG_UDB_PA0_CFG2
#define I2CMaster_scl__PA__CFG3 CYREG_UDB_PA0_CFG3
#define I2CMaster_scl__PA__CFG4 CYREG_UDB_PA0_CFG4
#define I2CMaster_scl__PA__CFG5 CYREG_UDB_PA0_CFG5
#define I2CMaster_scl__PA__CFG6 CYREG_UDB_PA0_CFG6
#define I2CMaster_scl__PA__CFG7 CYREG_UDB_PA0_CFG7
#define I2CMaster_scl__PA__CFG8 CYREG_UDB_PA0_CFG8
#define I2CMaster_scl__PA__CFG9 CYREG_UDB_PA0_CFG9
#define I2CMaster_scl__PC CYREG_PRT0_PC
#define I2CMaster_scl__PC2 CYREG_PRT0_PC2
#define I2CMaster_scl__PORT 0u
#define I2CMaster_scl__PS CYREG_PRT0_PS
#define I2CMaster_scl__SHIFT 4u

/* I2CMaster_sda */
#define I2CMaster_sda__0__DM__MASK 0x38000u
#define I2CMaster_sda__0__DM__SHIFT 15u
#define I2CMaster_sda__0__DR CYREG_PRT0_DR
#define I2CMaster_sda__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define I2CMaster_sda__0__HSIOM_GPIO 0u
#define I2CMaster_sda__0__HSIOM_I2C 14u
#define I2CMaster_sda__0__HSIOM_I2C_SDA 14u
#define I2CMaster_sda__0__HSIOM_MASK 0x00F00000u
#define I2CMaster_sda__0__HSIOM_SHIFT 20u
#define I2CMaster_sda__0__HSIOM_SPI 15u
#define I2CMaster_sda__0__HSIOM_SPI_MISO 15u
#define I2CMaster_sda__0__HSIOM_UART 9u
#define I2CMaster_sda__0__HSIOM_UART_TX 9u
#define I2CMaster_sda__0__INTCFG CYREG_PRT0_INTCFG
#define I2CMaster_sda__0__INTSTAT CYREG_PRT0_INTSTAT
#define I2CMaster_sda__0__MASK 0x20u
#define I2CMaster_sda__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define I2CMaster_sda__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define I2CMaster_sda__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define I2CMaster_sda__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define I2CMaster_sda__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define I2CMaster_sda__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define I2CMaster_sda__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define I2CMaster_sda__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define I2CMaster_sda__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define I2CMaster_sda__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define I2CMaster_sda__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define I2CMaster_sda__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define I2CMaster_sda__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define I2CMaster_sda__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define I2CMaster_sda__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define I2CMaster_sda__0__PC CYREG_PRT0_PC
#define I2CMaster_sda__0__PC2 CYREG_PRT0_PC2
#define I2CMaster_sda__0__PORT 0u
#define I2CMaster_sda__0__PS CYREG_PRT0_PS
#define I2CMaster_sda__0__SHIFT 5u
#define I2CMaster_sda__DR CYREG_PRT0_DR
#define I2CMaster_sda__INTCFG CYREG_PRT0_INTCFG
#define I2CMaster_sda__INTSTAT CYREG_PRT0_INTSTAT
#define I2CMaster_sda__MASK 0x20u
#define I2CMaster_sda__PA__CFG0 CYREG_UDB_PA0_CFG0
#define I2CMaster_sda__PA__CFG1 CYREG_UDB_PA0_CFG1
#define I2CMaster_sda__PA__CFG10 CYREG_UDB_PA0_CFG10
#define I2CMaster_sda__PA__CFG11 CYREG_UDB_PA0_CFG11
#define I2CMaster_sda__PA__CFG12 CYREG_UDB_PA0_CFG12
#define I2CMaster_sda__PA__CFG13 CYREG_UDB_PA0_CFG13
#define I2CMaster_sda__PA__CFG14 CYREG_UDB_PA0_CFG14
#define I2CMaster_sda__PA__CFG2 CYREG_UDB_PA0_CFG2
#define I2CMaster_sda__PA__CFG3 CYREG_UDB_PA0_CFG3
#define I2CMaster_sda__PA__CFG4 CYREG_UDB_PA0_CFG4
#define I2CMaster_sda__PA__CFG5 CYREG_UDB_PA0_CFG5
#define I2CMaster_sda__PA__CFG6 CYREG_UDB_PA0_CFG6
#define I2CMaster_sda__PA__CFG7 CYREG_UDB_PA0_CFG7
#define I2CMaster_sda__PA__CFG8 CYREG_UDB_PA0_CFG8
#define I2CMaster_sda__PA__CFG9 CYREG_UDB_PA0_CFG9
#define I2CMaster_sda__PC CYREG_PRT0_PC
#define I2CMaster_sda__PC2 CYREG_PRT0_PC2
#define I2CMaster_sda__PORT 0u
#define I2CMaster_sda__PS CYREG_PRT0_PS
#define I2CMaster_sda__SHIFT 5u

/* PWM_Clock */
#define PWM_Clock__DIVIDER_MASK 0x0000FFFFu
#define PWM_Clock__ENABLE CYREG_CLK_DIVIDER_A02
#define PWM_Clock__ENABLE_MASK 0x80000000u
#define PWM_Clock__MASK 0x80000000u
#define PWM_Clock__REGISTER CYREG_CLK_DIVIDER_A02

/* QuadDec_1_cy_m0s8_tcpwm_1 */
#define QuadDec_1_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT0_CC
#define QuadDec_1_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT0_CC_BUFF
#define QuadDec_1_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT0_COUNTER
#define QuadDec_1_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT0_CTRL
#define QuadDec_1_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT0_INTR
#define QuadDec_1_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT0_INTR_MASK
#define QuadDec_1_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT0_INTR_MASKED
#define QuadDec_1_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT0_INTR_SET
#define QuadDec_1_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT0_PERIOD
#define QuadDec_1_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT0_PERIOD_BUFF
#define QuadDec_1_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT0_STATUS
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x01u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 0u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x100u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 8u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x1000000u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 24u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x10000u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 16u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x01u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 0u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x01u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 0u
#define QuadDec_1_cy_m0s8_tcpwm_1__TCPWM_NUMBER 0u
#define QuadDec_1_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT0_TR_CTRL0
#define QuadDec_1_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT0_TR_CTRL1
#define QuadDec_1_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT0_TR_CTRL2

/* Quad_In_A */
#define Quad_In_A__0__DM__MASK 0x38000u
#define Quad_In_A__0__DM__SHIFT 15u
#define Quad_In_A__0__DR CYREG_PRT1_DR
#define Quad_In_A__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Quad_In_A__0__HSIOM_MASK 0x00F00000u
#define Quad_In_A__0__HSIOM_SHIFT 20u
#define Quad_In_A__0__INTCFG CYREG_PRT1_INTCFG
#define Quad_In_A__0__INTSTAT CYREG_PRT1_INTSTAT
#define Quad_In_A__0__MASK 0x20u
#define Quad_In_A__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Quad_In_A__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Quad_In_A__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Quad_In_A__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Quad_In_A__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Quad_In_A__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Quad_In_A__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Quad_In_A__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Quad_In_A__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Quad_In_A__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Quad_In_A__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Quad_In_A__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Quad_In_A__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Quad_In_A__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Quad_In_A__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Quad_In_A__0__PC CYREG_PRT1_PC
#define Quad_In_A__0__PC2 CYREG_PRT1_PC2
#define Quad_In_A__0__PORT 1u
#define Quad_In_A__0__PS CYREG_PRT1_PS
#define Quad_In_A__0__SHIFT 5u
#define Quad_In_A__DR CYREG_PRT1_DR
#define Quad_In_A__INTCFG CYREG_PRT1_INTCFG
#define Quad_In_A__INTSTAT CYREG_PRT1_INTSTAT
#define Quad_In_A__MASK 0x20u
#define Quad_In_A__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Quad_In_A__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Quad_In_A__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Quad_In_A__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Quad_In_A__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Quad_In_A__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Quad_In_A__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Quad_In_A__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Quad_In_A__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Quad_In_A__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Quad_In_A__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Quad_In_A__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Quad_In_A__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Quad_In_A__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Quad_In_A__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Quad_In_A__PC CYREG_PRT1_PC
#define Quad_In_A__PC2 CYREG_PRT1_PC2
#define Quad_In_A__PORT 1u
#define Quad_In_A__PS CYREG_PRT1_PS
#define Quad_In_A__SHIFT 5u

/* Quad_In_B */
#define Quad_In_B__0__DM__MASK 0x7000u
#define Quad_In_B__0__DM__SHIFT 12u
#define Quad_In_B__0__DR CYREG_PRT1_DR
#define Quad_In_B__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Quad_In_B__0__HSIOM_MASK 0x000F0000u
#define Quad_In_B__0__HSIOM_SHIFT 16u
#define Quad_In_B__0__INTCFG CYREG_PRT1_INTCFG
#define Quad_In_B__0__INTSTAT CYREG_PRT1_INTSTAT
#define Quad_In_B__0__MASK 0x10u
#define Quad_In_B__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Quad_In_B__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Quad_In_B__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Quad_In_B__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Quad_In_B__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Quad_In_B__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Quad_In_B__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Quad_In_B__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Quad_In_B__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Quad_In_B__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Quad_In_B__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Quad_In_B__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Quad_In_B__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Quad_In_B__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Quad_In_B__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Quad_In_B__0__PC CYREG_PRT1_PC
#define Quad_In_B__0__PC2 CYREG_PRT1_PC2
#define Quad_In_B__0__PORT 1u
#define Quad_In_B__0__PS CYREG_PRT1_PS
#define Quad_In_B__0__SHIFT 4u
#define Quad_In_B__DR CYREG_PRT1_DR
#define Quad_In_B__INTCFG CYREG_PRT1_INTCFG
#define Quad_In_B__INTSTAT CYREG_PRT1_INTSTAT
#define Quad_In_B__MASK 0x10u
#define Quad_In_B__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Quad_In_B__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Quad_In_B__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Quad_In_B__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Quad_In_B__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Quad_In_B__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Quad_In_B__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Quad_In_B__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Quad_In_B__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Quad_In_B__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Quad_In_B__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Quad_In_B__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Quad_In_B__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Quad_In_B__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Quad_In_B__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Quad_In_B__PC CYREG_PRT1_PC
#define Quad_In_B__PC2 CYREG_PRT1_PC2
#define Quad_In_B__PORT 1u
#define Quad_In_B__PS CYREG_PRT1_PS
#define Quad_In_B__SHIFT 4u

/* UD_Signal */
#define UD_Signal__0__DM__MASK 0x7000u
#define UD_Signal__0__DM__SHIFT 12u
#define UD_Signal__0__DR CYREG_PRT2_DR
#define UD_Signal__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define UD_Signal__0__HSIOM_MASK 0x000F0000u
#define UD_Signal__0__HSIOM_SHIFT 16u
#define UD_Signal__0__INTCFG CYREG_PRT2_INTCFG
#define UD_Signal__0__INTSTAT CYREG_PRT2_INTSTAT
#define UD_Signal__0__MASK 0x10u
#define UD_Signal__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define UD_Signal__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define UD_Signal__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define UD_Signal__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define UD_Signal__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define UD_Signal__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define UD_Signal__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define UD_Signal__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define UD_Signal__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define UD_Signal__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define UD_Signal__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define UD_Signal__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define UD_Signal__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define UD_Signal__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define UD_Signal__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define UD_Signal__0__PC CYREG_PRT2_PC
#define UD_Signal__0__PC2 CYREG_PRT2_PC2
#define UD_Signal__0__PORT 2u
#define UD_Signal__0__PS CYREG_PRT2_PS
#define UD_Signal__0__SHIFT 4u
#define UD_Signal__DR CYREG_PRT2_DR
#define UD_Signal__INTCFG CYREG_PRT2_INTCFG
#define UD_Signal__INTSTAT CYREG_PRT2_INTSTAT
#define UD_Signal__MASK 0x10u
#define UD_Signal__PA__CFG0 CYREG_UDB_PA2_CFG0
#define UD_Signal__PA__CFG1 CYREG_UDB_PA2_CFG1
#define UD_Signal__PA__CFG10 CYREG_UDB_PA2_CFG10
#define UD_Signal__PA__CFG11 CYREG_UDB_PA2_CFG11
#define UD_Signal__PA__CFG12 CYREG_UDB_PA2_CFG12
#define UD_Signal__PA__CFG13 CYREG_UDB_PA2_CFG13
#define UD_Signal__PA__CFG14 CYREG_UDB_PA2_CFG14
#define UD_Signal__PA__CFG2 CYREG_UDB_PA2_CFG2
#define UD_Signal__PA__CFG3 CYREG_UDB_PA2_CFG3
#define UD_Signal__PA__CFG4 CYREG_UDB_PA2_CFG4
#define UD_Signal__PA__CFG5 CYREG_UDB_PA2_CFG5
#define UD_Signal__PA__CFG6 CYREG_UDB_PA2_CFG6
#define UD_Signal__PA__CFG7 CYREG_UDB_PA2_CFG7
#define UD_Signal__PA__CFG8 CYREG_UDB_PA2_CFG8
#define UD_Signal__PA__CFG9 CYREG_UDB_PA2_CFG9
#define UD_Signal__PC CYREG_PRT2_PC
#define UD_Signal__PC2 CYREG_PRT2_PC2
#define UD_Signal__PORT 2u
#define UD_Signal__PS CYREG_PRT2_PS
#define UD_Signal__SHIFT 4u

/* Quad_Clock */
#define Quad_Clock__DIVIDER_MASK 0x0000FFFFu
#define Quad_Clock__ENABLE CYREG_CLK_DIVIDER_C00
#define Quad_Clock__ENABLE_MASK 0x80000000u
#define Quad_Clock__MASK 0x80000000u
#define Quad_Clock__REGISTER CYREG_CLK_DIVIDER_C00

/* ADC_SAR_SEQ_Bypass */
#define ADC_SAR_SEQ_Bypass__0__DM__MASK 0xE00000u
#define ADC_SAR_SEQ_Bypass__0__DM__SHIFT 21u
#define ADC_SAR_SEQ_Bypass__0__DR CYREG_PRT1_DR
#define ADC_SAR_SEQ_Bypass__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define ADC_SAR_SEQ_Bypass__0__HSIOM_MASK 0xF0000000u
#define ADC_SAR_SEQ_Bypass__0__HSIOM_SHIFT 28u
#define ADC_SAR_SEQ_Bypass__0__INTCFG CYREG_PRT1_INTCFG
#define ADC_SAR_SEQ_Bypass__0__INTSTAT CYREG_PRT1_INTSTAT
#define ADC_SAR_SEQ_Bypass__0__MASK 0x80u
#define ADC_SAR_SEQ_Bypass__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define ADC_SAR_SEQ_Bypass__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define ADC_SAR_SEQ_Bypass__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define ADC_SAR_SEQ_Bypass__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define ADC_SAR_SEQ_Bypass__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define ADC_SAR_SEQ_Bypass__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define ADC_SAR_SEQ_Bypass__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define ADC_SAR_SEQ_Bypass__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define ADC_SAR_SEQ_Bypass__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define ADC_SAR_SEQ_Bypass__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define ADC_SAR_SEQ_Bypass__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define ADC_SAR_SEQ_Bypass__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define ADC_SAR_SEQ_Bypass__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define ADC_SAR_SEQ_Bypass__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define ADC_SAR_SEQ_Bypass__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define ADC_SAR_SEQ_Bypass__0__PC CYREG_PRT1_PC
#define ADC_SAR_SEQ_Bypass__0__PC2 CYREG_PRT1_PC2
#define ADC_SAR_SEQ_Bypass__0__PORT 1u
#define ADC_SAR_SEQ_Bypass__0__PS CYREG_PRT1_PS
#define ADC_SAR_SEQ_Bypass__0__SHIFT 7u
#define ADC_SAR_SEQ_Bypass__DR CYREG_PRT1_DR
#define ADC_SAR_SEQ_Bypass__INTCFG CYREG_PRT1_INTCFG
#define ADC_SAR_SEQ_Bypass__INTSTAT CYREG_PRT1_INTSTAT
#define ADC_SAR_SEQ_Bypass__MASK 0x80u
#define ADC_SAR_SEQ_Bypass__PA__CFG0 CYREG_UDB_PA1_CFG0
#define ADC_SAR_SEQ_Bypass__PA__CFG1 CYREG_UDB_PA1_CFG1
#define ADC_SAR_SEQ_Bypass__PA__CFG10 CYREG_UDB_PA1_CFG10
#define ADC_SAR_SEQ_Bypass__PA__CFG11 CYREG_UDB_PA1_CFG11
#define ADC_SAR_SEQ_Bypass__PA__CFG12 CYREG_UDB_PA1_CFG12
#define ADC_SAR_SEQ_Bypass__PA__CFG13 CYREG_UDB_PA1_CFG13
#define ADC_SAR_SEQ_Bypass__PA__CFG14 CYREG_UDB_PA1_CFG14
#define ADC_SAR_SEQ_Bypass__PA__CFG2 CYREG_UDB_PA1_CFG2
#define ADC_SAR_SEQ_Bypass__PA__CFG3 CYREG_UDB_PA1_CFG3
#define ADC_SAR_SEQ_Bypass__PA__CFG4 CYREG_UDB_PA1_CFG4
#define ADC_SAR_SEQ_Bypass__PA__CFG5 CYREG_UDB_PA1_CFG5
#define ADC_SAR_SEQ_Bypass__PA__CFG6 CYREG_UDB_PA1_CFG6
#define ADC_SAR_SEQ_Bypass__PA__CFG7 CYREG_UDB_PA1_CFG7
#define ADC_SAR_SEQ_Bypass__PA__CFG8 CYREG_UDB_PA1_CFG8
#define ADC_SAR_SEQ_Bypass__PA__CFG9 CYREG_UDB_PA1_CFG9
#define ADC_SAR_SEQ_Bypass__PC CYREG_PRT1_PC
#define ADC_SAR_SEQ_Bypass__PC2 CYREG_PRT1_PC2
#define ADC_SAR_SEQ_Bypass__PORT 1u
#define ADC_SAR_SEQ_Bypass__PS CYREG_PRT1_PS
#define ADC_SAR_SEQ_Bypass__SHIFT 7u

/* ADC_SAR_SEQ_cy_psoc4_sar */
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_ANA_TRIM CYREG_SAR_ANA_TRIM
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG00 CYREG_SAR_CHAN_CONFIG00
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG01 CYREG_SAR_CHAN_CONFIG01
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG02 CYREG_SAR_CHAN_CONFIG02
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG03 CYREG_SAR_CHAN_CONFIG03
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG04 CYREG_SAR_CHAN_CONFIG04
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG05 CYREG_SAR_CHAN_CONFIG05
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG06 CYREG_SAR_CHAN_CONFIG06
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_CONFIG07 CYREG_SAR_CHAN_CONFIG07
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_EN CYREG_SAR_CHAN_EN
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT_VALID CYREG_SAR_CHAN_RESULT_VALID
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT00 CYREG_SAR_CHAN_RESULT00
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT01 CYREG_SAR_CHAN_RESULT01
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT02 CYREG_SAR_CHAN_RESULT02
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT03 CYREG_SAR_CHAN_RESULT03
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT04 CYREG_SAR_CHAN_RESULT04
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT05 CYREG_SAR_CHAN_RESULT05
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT06 CYREG_SAR_CHAN_RESULT06
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_RESULT07 CYREG_SAR_CHAN_RESULT07
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK_VALID CYREG_SAR_CHAN_WORK_VALID
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK00 CYREG_SAR_CHAN_WORK00
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK01 CYREG_SAR_CHAN_WORK01
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK02 CYREG_SAR_CHAN_WORK02
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK03 CYREG_SAR_CHAN_WORK03
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK04 CYREG_SAR_CHAN_WORK04
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK05 CYREG_SAR_CHAN_WORK05
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK06 CYREG_SAR_CHAN_WORK06
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CHAN_WORK07 CYREG_SAR_CHAN_WORK07
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_CTRL CYREG_SAR_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_DFT_CTRL CYREG_SAR_DFT_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_INTR CYREG_SAR_INTR
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_INTR_CAUSE CYREG_SAR_INTR_CAUSE
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_INTR_MASK CYREG_SAR_INTR_MASK
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_INTR_MASKED CYREG_SAR_INTR_MASKED
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_INTR_SET CYREG_SAR_INTR_SET
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_MUX_SWITCH_HW_CTRL CYREG_SAR_MUX_SWITCH_HW_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_MUX_SWITCH0 CYREG_SAR_MUX_SWITCH0
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_NUMBER 0u
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_PUMP_CTRL CYREG_SAR_PUMP_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_RANGE_COND CYREG_SAR_RANGE_COND
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_RANGE_INTR CYREG_SAR_RANGE_INTR
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_RANGE_INTR_MASK CYREG_SAR_RANGE_INTR_MASK
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_RANGE_INTR_MASKED CYREG_SAR_RANGE_INTR_MASKED
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_RANGE_INTR_SET CYREG_SAR_RANGE_INTR_SET
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_RANGE_THRES CYREG_SAR_RANGE_THRES
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SAMPLE_CTRL CYREG_SAR_SAMPLE_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SAMPLE_TIME01 CYREG_SAR_SAMPLE_TIME01
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SAMPLE_TIME23 CYREG_SAR_SAMPLE_TIME23
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SATURATE_INTR CYREG_SAR_SATURATE_INTR
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SATURATE_INTR_MASK CYREG_SAR_SATURATE_INTR_MASK
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SATURATE_INTR_MASKED CYREG_SAR_SATURATE_INTR_MASKED
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_SATURATE_INTR_SET CYREG_SAR_SATURATE_INTR_SET
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_START_CTRL CYREG_SAR_START_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_STATUS CYREG_SAR_STATUS
#define ADC_SAR_SEQ_cy_psoc4_sar__SAR_WOUNDING CYREG_SAR_WOUNDING

/* ADC_SAR_SEQ_cy_psoc4_sarmux_8 */
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__CH_0_PIN 7
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__CH_0_PORT 0
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__CH_1_PIN 6
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__CH_1_PORT 0
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__CH_2_PIN 2
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__CH_2_PORT 1
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG00 CYREG_SAR_CHAN_CONFIG00
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG01 CYREG_SAR_CHAN_CONFIG01
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG02 CYREG_SAR_CHAN_CONFIG02
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG03 CYREG_SAR_CHAN_CONFIG03
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG04 CYREG_SAR_CHAN_CONFIG04
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG05 CYREG_SAR_CHAN_CONFIG05
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG06 CYREG_SAR_CHAN_CONFIG06
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG07 CYREG_SAR_CHAN_CONFIG07
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_EN CYREG_SAR_CHAN_EN
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT_VALID CYREG_SAR_CHAN_RESULT_VALID
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT00 CYREG_SAR_CHAN_RESULT00
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT01 CYREG_SAR_CHAN_RESULT01
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT02 CYREG_SAR_CHAN_RESULT02
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT03 CYREG_SAR_CHAN_RESULT03
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT04 CYREG_SAR_CHAN_RESULT04
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT05 CYREG_SAR_CHAN_RESULT05
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT06 CYREG_SAR_CHAN_RESULT06
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_RESULT07 CYREG_SAR_CHAN_RESULT07
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK_VALID CYREG_SAR_CHAN_WORK_VALID
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK00 CYREG_SAR_CHAN_WORK00
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK01 CYREG_SAR_CHAN_WORK01
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK02 CYREG_SAR_CHAN_WORK02
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK03 CYREG_SAR_CHAN_WORK03
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK04 CYREG_SAR_CHAN_WORK04
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK05 CYREG_SAR_CHAN_WORK05
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK06 CYREG_SAR_CHAN_WORK06
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_CHAN_WORK07 CYREG_SAR_CHAN_WORK07
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_INJ_CHAN_CONFIG CYREG_SAR_INJ_CHAN_CONFIG
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_INJ_RESULT CYREG_SAR_INJ_RESULT
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_MUX_SWITCH_HW_CTRL CYREG_SAR_MUX_SWITCH_HW_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_MUX_SWITCH0 CYREG_SAR_MUX_SWITCH0
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__SAR_START_CTRL CYREG_SAR_START_CTRL
#define ADC_SAR_SEQ_cy_psoc4_sarmux_8__VNEG 0

/* ADC_SAR_SEQ_intClock */
#define ADC_SAR_SEQ_intClock__DIVIDER_MASK 0x0000FFFFu
#define ADC_SAR_SEQ_intClock__ENABLE CYREG_CLK_DIVIDER_A01
#define ADC_SAR_SEQ_intClock__ENABLE_MASK 0x80000000u
#define ADC_SAR_SEQ_intClock__MASK 0x80000000u
#define ADC_SAR_SEQ_intClock__REGISTER CYREG_CLK_DIVIDER_A01

/* ADC_SAR_SEQ_IRQ */
#define ADC_SAR_SEQ_IRQ__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ADC_SAR_SEQ_IRQ__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ADC_SAR_SEQ_IRQ__INTC_MASK 0x4000u
#define ADC_SAR_SEQ_IRQ__INTC_NUMBER 14u
#define ADC_SAR_SEQ_IRQ__INTC_PRIOR_MASK 0xC00000u
#define ADC_SAR_SEQ_IRQ__INTC_PRIOR_NUM 3u
#define ADC_SAR_SEQ_IRQ__INTC_PRIOR_REG CYREG_CM0_IPR3
#define ADC_SAR_SEQ_IRQ__INTC_SET_EN_REG CYREG_CM0_ISER
#define ADC_SAR_SEQ_IRQ__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ROSSerial_UART_Clock */
#define ROSSerial_UART_Clock__DIVIDER_MASK 0x0000FFFFu
#define ROSSerial_UART_Clock__ENABLE CYREG_CLK_DIVIDER_B01
#define ROSSerial_UART_Clock__ENABLE_MASK 0x80000000u
#define ROSSerial_UART_Clock__MASK 0x80000000u
#define ROSSerial_UART_Clock__REGISTER CYREG_CLK_DIVIDER_B01

/* ROSSerial_UART_rx */
#define ROSSerial_UART_rx__0__DM__MASK 0x07u
#define ROSSerial_UART_rx__0__DM__SHIFT 0u
#define ROSSerial_UART_rx__0__DR CYREG_PRT4_DR
#define ROSSerial_UART_rx__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define ROSSerial_UART_rx__0__HSIOM_GPIO 0u
#define ROSSerial_UART_rx__0__HSIOM_I2C 14u
#define ROSSerial_UART_rx__0__HSIOM_I2C_SCL 14u
#define ROSSerial_UART_rx__0__HSIOM_MASK 0x0000000Fu
#define ROSSerial_UART_rx__0__HSIOM_SHIFT 0u
#define ROSSerial_UART_rx__0__HSIOM_SPI 15u
#define ROSSerial_UART_rx__0__HSIOM_SPI_MOSI 15u
#define ROSSerial_UART_rx__0__HSIOM_UART 9u
#define ROSSerial_UART_rx__0__HSIOM_UART_RX 9u
#define ROSSerial_UART_rx__0__INTCFG CYREG_PRT4_INTCFG
#define ROSSerial_UART_rx__0__INTSTAT CYREG_PRT4_INTSTAT
#define ROSSerial_UART_rx__0__MASK 0x01u
#define ROSSerial_UART_rx__0__PC CYREG_PRT4_PC
#define ROSSerial_UART_rx__0__PC2 CYREG_PRT4_PC2
#define ROSSerial_UART_rx__0__PORT 4u
#define ROSSerial_UART_rx__0__PS CYREG_PRT4_PS
#define ROSSerial_UART_rx__0__SHIFT 0u
#define ROSSerial_UART_rx__DR CYREG_PRT4_DR
#define ROSSerial_UART_rx__INTCFG CYREG_PRT4_INTCFG
#define ROSSerial_UART_rx__INTSTAT CYREG_PRT4_INTSTAT
#define ROSSerial_UART_rx__MASK 0x01u
#define ROSSerial_UART_rx__PC CYREG_PRT4_PC
#define ROSSerial_UART_rx__PC2 CYREG_PRT4_PC2
#define ROSSerial_UART_rx__PORT 4u
#define ROSSerial_UART_rx__PS CYREG_PRT4_PS
#define ROSSerial_UART_rx__SHIFT 0u

/* ROSSerial_UART_SCB */
#define ROSSerial_UART_SCB__BIST_CONTROL CYREG_SCB0_BIST_CONTROL
#define ROSSerial_UART_SCB__BIST_DATA CYREG_SCB0_BIST_DATA
#define ROSSerial_UART_SCB__CTRL CYREG_SCB0_CTRL
#define ROSSerial_UART_SCB__EZ_DATA00 CYREG_SCB0_EZ_DATA00
#define ROSSerial_UART_SCB__EZ_DATA01 CYREG_SCB0_EZ_DATA01
#define ROSSerial_UART_SCB__EZ_DATA02 CYREG_SCB0_EZ_DATA02
#define ROSSerial_UART_SCB__EZ_DATA03 CYREG_SCB0_EZ_DATA03
#define ROSSerial_UART_SCB__EZ_DATA04 CYREG_SCB0_EZ_DATA04
#define ROSSerial_UART_SCB__EZ_DATA05 CYREG_SCB0_EZ_DATA05
#define ROSSerial_UART_SCB__EZ_DATA06 CYREG_SCB0_EZ_DATA06
#define ROSSerial_UART_SCB__EZ_DATA07 CYREG_SCB0_EZ_DATA07
#define ROSSerial_UART_SCB__EZ_DATA08 CYREG_SCB0_EZ_DATA08
#define ROSSerial_UART_SCB__EZ_DATA09 CYREG_SCB0_EZ_DATA09
#define ROSSerial_UART_SCB__EZ_DATA10 CYREG_SCB0_EZ_DATA10
#define ROSSerial_UART_SCB__EZ_DATA11 CYREG_SCB0_EZ_DATA11
#define ROSSerial_UART_SCB__EZ_DATA12 CYREG_SCB0_EZ_DATA12
#define ROSSerial_UART_SCB__EZ_DATA13 CYREG_SCB0_EZ_DATA13
#define ROSSerial_UART_SCB__EZ_DATA14 CYREG_SCB0_EZ_DATA14
#define ROSSerial_UART_SCB__EZ_DATA15 CYREG_SCB0_EZ_DATA15
#define ROSSerial_UART_SCB__EZ_DATA16 CYREG_SCB0_EZ_DATA16
#define ROSSerial_UART_SCB__EZ_DATA17 CYREG_SCB0_EZ_DATA17
#define ROSSerial_UART_SCB__EZ_DATA18 CYREG_SCB0_EZ_DATA18
#define ROSSerial_UART_SCB__EZ_DATA19 CYREG_SCB0_EZ_DATA19
#define ROSSerial_UART_SCB__EZ_DATA20 CYREG_SCB0_EZ_DATA20
#define ROSSerial_UART_SCB__EZ_DATA21 CYREG_SCB0_EZ_DATA21
#define ROSSerial_UART_SCB__EZ_DATA22 CYREG_SCB0_EZ_DATA22
#define ROSSerial_UART_SCB__EZ_DATA23 CYREG_SCB0_EZ_DATA23
#define ROSSerial_UART_SCB__EZ_DATA24 CYREG_SCB0_EZ_DATA24
#define ROSSerial_UART_SCB__EZ_DATA25 CYREG_SCB0_EZ_DATA25
#define ROSSerial_UART_SCB__EZ_DATA26 CYREG_SCB0_EZ_DATA26
#define ROSSerial_UART_SCB__EZ_DATA27 CYREG_SCB0_EZ_DATA27
#define ROSSerial_UART_SCB__EZ_DATA28 CYREG_SCB0_EZ_DATA28
#define ROSSerial_UART_SCB__EZ_DATA29 CYREG_SCB0_EZ_DATA29
#define ROSSerial_UART_SCB__EZ_DATA30 CYREG_SCB0_EZ_DATA30
#define ROSSerial_UART_SCB__EZ_DATA31 CYREG_SCB0_EZ_DATA31
#define ROSSerial_UART_SCB__I2C_CFG CYREG_SCB0_I2C_CFG
#define ROSSerial_UART_SCB__I2C_CTRL CYREG_SCB0_I2C_CTRL
#define ROSSerial_UART_SCB__I2C_M_CMD CYREG_SCB0_I2C_M_CMD
#define ROSSerial_UART_SCB__I2C_S_CMD CYREG_SCB0_I2C_S_CMD
#define ROSSerial_UART_SCB__I2C_STATUS CYREG_SCB0_I2C_STATUS
#define ROSSerial_UART_SCB__INTR_CAUSE CYREG_SCB0_INTR_CAUSE
#define ROSSerial_UART_SCB__INTR_I2C_EC CYREG_SCB0_INTR_I2C_EC
#define ROSSerial_UART_SCB__INTR_I2C_EC_MASK CYREG_SCB0_INTR_I2C_EC_MASK
#define ROSSerial_UART_SCB__INTR_I2C_EC_MASKED CYREG_SCB0_INTR_I2C_EC_MASKED
#define ROSSerial_UART_SCB__INTR_M CYREG_SCB0_INTR_M
#define ROSSerial_UART_SCB__INTR_M_MASK CYREG_SCB0_INTR_M_MASK
#define ROSSerial_UART_SCB__INTR_M_MASKED CYREG_SCB0_INTR_M_MASKED
#define ROSSerial_UART_SCB__INTR_M_SET CYREG_SCB0_INTR_M_SET
#define ROSSerial_UART_SCB__INTR_RX CYREG_SCB0_INTR_RX
#define ROSSerial_UART_SCB__INTR_RX_MASK CYREG_SCB0_INTR_RX_MASK
#define ROSSerial_UART_SCB__INTR_RX_MASKED CYREG_SCB0_INTR_RX_MASKED
#define ROSSerial_UART_SCB__INTR_RX_SET CYREG_SCB0_INTR_RX_SET
#define ROSSerial_UART_SCB__INTR_S CYREG_SCB0_INTR_S
#define ROSSerial_UART_SCB__INTR_S_MASK CYREG_SCB0_INTR_S_MASK
#define ROSSerial_UART_SCB__INTR_S_MASKED CYREG_SCB0_INTR_S_MASKED
#define ROSSerial_UART_SCB__INTR_S_SET CYREG_SCB0_INTR_S_SET
#define ROSSerial_UART_SCB__INTR_SPI_EC CYREG_SCB0_INTR_SPI_EC
#define ROSSerial_UART_SCB__INTR_SPI_EC_MASK CYREG_SCB0_INTR_SPI_EC_MASK
#define ROSSerial_UART_SCB__INTR_SPI_EC_MASKED CYREG_SCB0_INTR_SPI_EC_MASKED
#define ROSSerial_UART_SCB__INTR_TX CYREG_SCB0_INTR_TX
#define ROSSerial_UART_SCB__INTR_TX_MASK CYREG_SCB0_INTR_TX_MASK
#define ROSSerial_UART_SCB__INTR_TX_MASKED CYREG_SCB0_INTR_TX_MASKED
#define ROSSerial_UART_SCB__INTR_TX_SET CYREG_SCB0_INTR_TX_SET
#define ROSSerial_UART_SCB__RX_CTRL CYREG_SCB0_RX_CTRL
#define ROSSerial_UART_SCB__RX_FIFO_CTRL CYREG_SCB0_RX_FIFO_CTRL
#define ROSSerial_UART_SCB__RX_FIFO_RD CYREG_SCB0_RX_FIFO_RD
#define ROSSerial_UART_SCB__RX_FIFO_RD_SILENT CYREG_SCB0_RX_FIFO_RD_SILENT
#define ROSSerial_UART_SCB__RX_FIFO_STATUS CYREG_SCB0_RX_FIFO_STATUS
#define ROSSerial_UART_SCB__RX_MATCH CYREG_SCB0_RX_MATCH
#define ROSSerial_UART_SCB__SPI_CTRL CYREG_SCB0_SPI_CTRL
#define ROSSerial_UART_SCB__SPI_STATUS CYREG_SCB0_SPI_STATUS
#define ROSSerial_UART_SCB__SS0_POSISTION 0u
#define ROSSerial_UART_SCB__SS1_POSISTION 1u
#define ROSSerial_UART_SCB__SS2_POSISTION 2u
#define ROSSerial_UART_SCB__SS3_POSISTION 3u
#define ROSSerial_UART_SCB__STATUS CYREG_SCB0_STATUS
#define ROSSerial_UART_SCB__TX_CTRL CYREG_SCB0_TX_CTRL
#define ROSSerial_UART_SCB__TX_FIFO_CTRL CYREG_SCB0_TX_FIFO_CTRL
#define ROSSerial_UART_SCB__TX_FIFO_STATUS CYREG_SCB0_TX_FIFO_STATUS
#define ROSSerial_UART_SCB__TX_FIFO_WR CYREG_SCB0_TX_FIFO_WR
#define ROSSerial_UART_SCB__UART_CTRL CYREG_SCB0_UART_CTRL
#define ROSSerial_UART_SCB__UART_RX_CTRL CYREG_SCB0_UART_RX_CTRL
#define ROSSerial_UART_SCB__UART_RX_STATUS CYREG_SCB0_UART_RX_STATUS
#define ROSSerial_UART_SCB__UART_TX_CTRL CYREG_SCB0_UART_TX_CTRL

/* ROSSerial_UART_SCB_IRQ */
#define ROSSerial_UART_SCB_IRQ__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ROSSerial_UART_SCB_IRQ__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ROSSerial_UART_SCB_IRQ__INTC_MASK 0x400u
#define ROSSerial_UART_SCB_IRQ__INTC_NUMBER 10u
#define ROSSerial_UART_SCB_IRQ__INTC_PRIOR_MASK 0xC00000u
#define ROSSerial_UART_SCB_IRQ__INTC_PRIOR_NUM 3u
#define ROSSerial_UART_SCB_IRQ__INTC_PRIOR_REG CYREG_CM0_IPR2
#define ROSSerial_UART_SCB_IRQ__INTC_SET_EN_REG CYREG_CM0_ISER
#define ROSSerial_UART_SCB_IRQ__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ROSSerial_UART_tx */
#define ROSSerial_UART_tx__0__DM__MASK 0x38u
#define ROSSerial_UART_tx__0__DM__SHIFT 3u
#define ROSSerial_UART_tx__0__DR CYREG_PRT4_DR
#define ROSSerial_UART_tx__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define ROSSerial_UART_tx__0__HSIOM_GPIO 0u
#define ROSSerial_UART_tx__0__HSIOM_I2C 14u
#define ROSSerial_UART_tx__0__HSIOM_I2C_SDA 14u
#define ROSSerial_UART_tx__0__HSIOM_MASK 0x000000F0u
#define ROSSerial_UART_tx__0__HSIOM_SHIFT 4u
#define ROSSerial_UART_tx__0__HSIOM_SPI 15u
#define ROSSerial_UART_tx__0__HSIOM_SPI_MISO 15u
#define ROSSerial_UART_tx__0__HSIOM_UART 9u
#define ROSSerial_UART_tx__0__HSIOM_UART_TX 9u
#define ROSSerial_UART_tx__0__INTCFG CYREG_PRT4_INTCFG
#define ROSSerial_UART_tx__0__INTSTAT CYREG_PRT4_INTSTAT
#define ROSSerial_UART_tx__0__MASK 0x02u
#define ROSSerial_UART_tx__0__PC CYREG_PRT4_PC
#define ROSSerial_UART_tx__0__PC2 CYREG_PRT4_PC2
#define ROSSerial_UART_tx__0__PORT 4u
#define ROSSerial_UART_tx__0__PS CYREG_PRT4_PS
#define ROSSerial_UART_tx__0__SHIFT 1u
#define ROSSerial_UART_tx__DR CYREG_PRT4_DR
#define ROSSerial_UART_tx__INTCFG CYREG_PRT4_INTCFG
#define ROSSerial_UART_tx__INTSTAT CYREG_PRT4_INTSTAT
#define ROSSerial_UART_tx__MASK 0x02u
#define ROSSerial_UART_tx__PC CYREG_PRT4_PC
#define ROSSerial_UART_tx__PC2 CYREG_PRT4_PC2
#define ROSSerial_UART_tx__PORT 4u
#define ROSSerial_UART_tx__PS CYREG_PRT4_PS
#define ROSSerial_UART_tx__SHIFT 1u

/* Transimpedance_cy_psoc4_abuf */
#define Transimpedance_cy_psoc4_abuf__COMP_STAT CYREG_CTBM_COMP_STAT
#define Transimpedance_cy_psoc4_abuf__COMP_STAT_SHIFT 0u
#define Transimpedance_cy_psoc4_abuf__CTBM_CTB_CTRL CYREG_CTBM_CTB_CTRL
#define Transimpedance_cy_psoc4_abuf__INTR CYREG_CTBM_INTR
#define Transimpedance_cy_psoc4_abuf__INTR_MASK CYREG_CTBM_INTR_MASK
#define Transimpedance_cy_psoc4_abuf__INTR_MASK_SHIFT 0u
#define Transimpedance_cy_psoc4_abuf__INTR_MASKED CYREG_CTBM_INTR_MASKED
#define Transimpedance_cy_psoc4_abuf__INTR_MASKED_SHIFT 0u
#define Transimpedance_cy_psoc4_abuf__INTR_SET CYREG_CTBM_INTR_SET
#define Transimpedance_cy_psoc4_abuf__INTR_SET_SHIFT 0u
#define Transimpedance_cy_psoc4_abuf__INTR_SHIFT 0u
#define Transimpedance_cy_psoc4_abuf__OA_COMP_TRIM CYREG_CTBM_OA0_COMP_TRIM
#define Transimpedance_cy_psoc4_abuf__OA_NUMBER 0u
#define Transimpedance_cy_psoc4_abuf__OA_OFFSET_TRIM CYREG_CTBM_OA0_OFFSET_TRIM
#define Transimpedance_cy_psoc4_abuf__OA_RES_CTRL CYREG_CTBM_OA_RES0_CTRL
#define Transimpedance_cy_psoc4_abuf__OA_SLOPE_OFFSET_TRIM CYREG_CTBM_OA0_SLOPE_OFFSET_TRIM
#define Transimpedance_cy_psoc4_abuf__OA_SW CYREG_CTBM_OA0_SW
#define Transimpedance_cy_psoc4_abuf__OA_SW_CLEAR CYREG_CTBM_OA0_SW_CLEAR

/* Stepper_Control */
#define Stepper_Control_Sync_ctrl_reg__1__MASK 0x02u
#define Stepper_Control_Sync_ctrl_reg__1__POS 1
#define Stepper_Control_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_02
#define Stepper_Control_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_02
#define Stepper_Control_Sync_ctrl_reg__2__MASK 0x04u
#define Stepper_Control_Sync_ctrl_reg__2__POS 2
#define Stepper_Control_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define Stepper_Control_Sync_ctrl_reg__CONTROL_REG CYREG_UDB_W8_CTL_02
#define Stepper_Control_Sync_ctrl_reg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define Stepper_Control_Sync_ctrl_reg__COUNT_REG CYREG_UDB_W8_CTL_02
#define Stepper_Control_Sync_ctrl_reg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define Stepper_Control_Sync_ctrl_reg__MASK 0x06u
#define Stepper_Control_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define Stepper_Control_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define Stepper_Control_Sync_ctrl_reg__PERIOD_REG CYREG_UDB_W8_MSK_02

/* Miscellaneous */
#define CY_PROJECT_NAME "RosOnAStick"
#define CY_VERSION "PSoC Creator  3.3 CP3"
#define CYDEV_BANDGAP_VOLTAGE 1.024
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 19u
#define CYDEV_CHIP_DIE_PSOC4A 11u
#define CYDEV_CHIP_DIE_PSOC5LP 18u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 11u
#define CYDEV_CHIP_MEMBER_4C 16u
#define CYDEV_CHIP_MEMBER_4D 7u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 12u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 10u
#define CYDEV_CHIP_MEMBER_4I 15u
#define CYDEV_CHIP_MEMBER_4J 8u
#define CYDEV_CHIP_MEMBER_4K 9u
#define CYDEV_CHIP_MEMBER_4L 14u
#define CYDEV_CHIP_MEMBER_4M 13u
#define CYDEV_CHIP_MEMBER_4N 6u
#define CYDEV_CHIP_MEMBER_4O 5u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 18u
#define CYDEV_CHIP_MEMBER_5B 17u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4O_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DFT_SELECT_CLK0 1u
#define CYDEV_DFT_SELECT_CLK1 2u
#define CYDEV_HEAP_SIZE 0x0100
#define CYDEV_IMO_TRIMMED_BY_USB 0u
#define CYDEV_IMO_TRIMMED_BY_WCO 0u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 2
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0400
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYDEV_WDT_GENERATE_ISR 0u
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
